@echo off

set OPENSSL_ROOT_DIR=%~dp0/3rd/3rd-libs/openssl-1.1.1t/x64-windows
%*

set VS_VERSION="Visual Studio 16 2019"
set ROOT_DIR=%~dp0
set POCO_DEBUG_DIR=%ROOT_DIR%/3rd/poco/build

@rem poco debug config
cd %ROOT_DIR%
mkdir "%POCO_DEBUG_DIR%" 2>nul
cd %POCO_DEBUG_DIR%

cmake -G %VS_VERSION% -A x64 -DENABLE_FOUNDATION=ON -DENABLE_CRYPTO=ON -DENABLE_NET=ON -DENABLE_UTIL=ON -DENABLE_NETSSL=ON -DENABLE_TESTS=ON -DENABLE_NETSSL_WIN=OFF -DENABLE_DATA=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_SQLITE=OFF -DENABLE_DATA_POSTGRESQL=OFF -DENABLE_ENCODINGS=OFF -DENABLE_ENCODINGS_COMPILER=OFF -DENABLE_JWT=OFF -DENABLE_XML=OFF -DENABLE_JSON=OFF -DENABLE_MONGODB=OFF -DENABLE_REDIS=OFF -DENABLE_PROMETHEUS=OFF -DENABLE_PDF=OFF -DENABLE_ZIP=OFF -DENABLE_SEVENZIP=OFF -DENABLE_CPPPARSER=OFF -DENABLE_POCODOC=OFF -DENABLE_APACHECONNECTOR=OFF -DENABLE_PAGECOMPILER=OFF -DENABLE_PAGECOMPILER_FILE2PAGE=OFF -DENABLE_ACTIVERECORD=OFF -DENABLE_ACTIVERECORD_COMPILER=OFF ../

pause