# 项目名字
SET(CURRENT_TARGET_NAME jsoncpp)

# 头文件目录
SET(CURRENT_PRIVATE_INCLUDE_DIRS
    # ...
)

SET(CURRENT_PUBLIC_INCLUDE_DIRS
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/include
)

# 宏定义、编译选项、链接库
IF(WIN32)
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        -DJSON_DLL_BUILD
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        -DJSONCPP_HAS_STRING_VIEW
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        # ...
    )
ELSE()
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        -DJSON_DLL_BUILD
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        -DJSONCPP_HAS_STRING_VIEW
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        # ...
    )
ENDIF()

# jsoncpp头文件
FILE(GLOB_RECURSE JSONCPP_INCLUDE_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/include/*.h
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/include/*.inl
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/include/*.hpp
)

# jsoncpp源文件
FILE(GLOB_RECURSE JSONCPP_SRC_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/src/lib_json/*.c
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/src/lib_json/*.cc
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp/src/lib_json/*.cpp
)

# 生成动态库
ADD_LIBRARY(${CURRENT_TARGET_NAME} SHARED ${JSONCPP_INCLUDE_LIST} ${JSONCPP_SRC_LIST})
PROJECT_TARGET_APPLY_COMMON_OPTIONS(${CURRENT_TARGET_NAME})
TARGET_INCLUDE_DIRECTORIES(${CURRENT_TARGET_NAME} PRIVATE ${CURRENT_PRIVATE_INCLUDE_DIRS})
TARGET_INCLUDE_DIRECTORIES(${CURRENT_TARGET_NAME} PUBLIC  ${CURRENT_PUBLIC_INCLUDE_DIRS})
TARGET_COMPILE_DEFINITIONS(${CURRENT_TARGET_NAME} PRIVATE ${CURRENT_PRIVATE_COMPILE_DEFINITIONS})
TARGET_COMPILE_DEFINITIONS(${CURRENT_TARGET_NAME} PUBLIC  ${CURRENT_PUBLIC_COMPILE_DEFINITIONS})
TARGET_COMPILE_OPTIONS(${CURRENT_TARGET_NAME}     PRIVATE ${CURRENT_COMPILE_OPTIONS})
TARGET_LINK_DIRECTORIES(${CURRENT_TARGET_NAME}    PRIVATE ${PROJECT_DEBUGGER_WORKING_DIRECTORY})
TARGET_LINK_LIBRARIES(${CURRENT_TARGET_NAME}      PUBLIC  ${CURRENT_LINK_LIBS})

# 其它设置
IF(WIN32)
    # MSVC运行库设置
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")

    # VS工程设置
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY FOLDER "projects")
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_DEBUGGER_WORKING_DIRECTORY}")

    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/jsoncpp PREFIX "jsoncpp"
        FILES ${JSONCPP_INCLUDE_LIST} ${JSONCPP_SRC_LIST})
ENDIF()