# 项目名字
SET(CURRENT_TARGET_NAME opencc_dict)

# 头文件目录
SET(CURRENT_INCLUDE_DIR
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc/src
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc/deps/tclap-1.2.5
)

# 宏定义、编译选项、链接库
IF(WIN32)
    # 宏定义
    SET(CURRENT_COMPILE_DEFINITIONS
        # ...
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        opencc
    )
ELSE()
    # 宏定义
    SET(CURRENT_COMPILE_DEFINITIONS
        # ...
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        opencc
    )
ENDIF()

# opencc_dict源文件
SET(OPENCC_DICT_SRC_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc/src/tools/DictConverter.cpp
)

# tclap源文件
FILE(GLOB_RECURSE TCLAP_SRC_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc/deps/tclap-1.2.5/*.h
)

# 生成可执行文件
ADD_EXECUTABLE(${CURRENT_TARGET_NAME} ${OPENCC_DICT_SRC_LIST} ${TCLAP_SRC_LIST})
PROJECT_TARGET_APPLY_COMMON_OPTIONS(${CURRENT_TARGET_NAME})
TARGET_INCLUDE_DIRECTORIES(${CURRENT_TARGET_NAME} PRIVATE ${CURRENT_INCLUDE_DIR})
TARGET_COMPILE_DEFINITIONS(${CURRENT_TARGET_NAME} PRIVATE ${CURRENT_COMPILE_DEFINITIONS})
TARGET_COMPILE_OPTIONS(${CURRENT_TARGET_NAME}     PRIVATE ${CURRENT_COMPILE_OPTIONS})
TARGET_LINK_DIRECTORIES(${CURRENT_TARGET_NAME}    PRIVATE ${PROJECT_DEBUGGER_WORKING_DIRECTORY})
TARGET_LINK_LIBRARIES(${CURRENT_TARGET_NAME}      PRIVATE ${CURRENT_LINK_LIBS})

# 其它设置
IF(WIN32)
    # MSVC运行库设置
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")

    # 导出所有符号设置
    # SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY WINDOWS_EXPORT_ALL_SYMBOLS True)
    # SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY ENABLE_EXPORTS True)

    # VS工程设置
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY FOLDER "projects")
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_DEBUGGER_WORKING_DIRECTORY}")

    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc/src/tools PREFIX "opencc_dict"
        FILES ${OPENCC_DICT_SRC_LIST})
    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/opencc/deps/tclap-1.2.5/tclap PREFIX "tclap"
        FILES ${TCLAP_SRC_LIST})
ENDIF()