# 项目名字
SET(CURRENT_TARGET_NAME curl)

SET(CURL_SOURCE_DIR "${CMAKE_PROJECT_ROOT_DIR}/3rd/curl")
SET(CURL_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/curl")

IF(NOT EXISTS "${CURL_SOURCE_DIR}/CMakeLists.txt")
    MESSAGE(FATAL_ERROR "curl source directory is missing: ${CURL_SOURCE_DIR}")
ENDIF()

IF(NOT TARGET OpenSSL::SSL)
    FIND_PACKAGE(OpenSSL REQUIRED)
ENDIF()

# curl 构建选项：第一版只保留 HTTP/HTTPS、OpenSSL、threaded DNS 和 multi 所需能力。
SET(BUILD_SHARED_LIBS           ON  CACHE BOOL "Build curl shared library" FORCE)
SET(BUILD_STATIC_LIBS           OFF CACHE BOOL "Do not build curl static library" FORCE)
SET(BUILD_CURL_EXE              OFF CACHE BOOL "Do not build curl command line tool" FORCE)
SET(BUILD_STATIC_CURL           OFF CACHE BOOL "Do not build static curl executable" FORCE)
SET(CURL_DISABLE_INSTALL        ON  CACHE BOOL "Do not install curl from the main project" FORCE)
SET(CURL_ENABLE_EXPORT_TARGET   OFF CACHE BOOL "Do not export curl package targets" FORCE)

SET(BUILD_EXAMPLES              OFF CACHE BOOL "Do not build curl examples" FORCE)
SET(BUILD_TESTING               OFF CACHE BOOL "Do not build curl tests" FORCE)
SET(CURL_BUILD_TESTING          OFF CACHE BOOL "Do not build curl tests" FORCE)
SET(BUILD_LIBCURL_DOCS          OFF CACHE BOOL "Do not build libcurl docs" FORCE)
SET(BUILD_MISC_DOCS             OFF CACHE BOOL "Do not build curl misc docs" FORCE)
SET(ENABLE_CURL_MANUAL          OFF CACHE BOOL "Do not build curl manual" FORCE)
SET(CURL_LINT                   OFF CACHE BOOL "Do not build curl lint targets" FORCE)

SET(HTTP_ONLY                   ON  CACHE BOOL "Build only HTTP/HTTPS protocols" FORCE)
SET(CURL_ENABLE_SSL             ON  CACHE BOOL "Enable TLS support" FORCE)
SET(CURL_USE_OPENSSL            ON  CACHE BOOL "Use OpenSSL TLS backend" FORCE)
SET(OPENSSL_USE_STATIC_LIBS     OFF CACHE BOOL "Link OpenSSL shared libraries" FORCE)
SET(CURL_USE_SCHANNEL           OFF CACHE BOOL "Disable Schannel TLS backend" FORCE)
SET(CURL_USE_MBEDTLS            OFF CACHE BOOL "Disable mbedTLS TLS backend" FORCE)
SET(CURL_USE_WOLFSSL            OFF CACHE BOOL "Disable wolfSSL TLS backend" FORCE)
SET(CURL_USE_GNUTLS             OFF CACHE BOOL "Disable GnuTLS TLS backend" FORCE)
SET(CURL_USE_RUSTLS             OFF CACHE BOOL "Disable Rustls TLS backend" FORCE)

SET(ENABLE_ARES                 OFF CACHE BOOL "Disable c-ares dependency" FORCE)
SET(ENABLE_THREADED_RESOLVER    ON  CACHE BOOL "Use threaded DNS resolver" FORCE)
SET(USE_NGHTTP2                 OFF CACHE BOOL "Disable HTTP/2 dependency" FORCE)
SET(USE_NGTCP2                  OFF CACHE BOOL "Disable HTTP/3 ngtcp2 dependency" FORCE)
SET(USE_QUICHE                  OFF CACHE BOOL "Disable HTTP/3 quiche dependency" FORCE)
SET(USE_LIBIDN2                 OFF CACHE BOOL "Disable libidn2 dependency" FORCE)
SET(CURL_USE_LIBPSL             OFF CACHE BOOL "Disable libpsl dependency" FORCE)
SET(CURL_USE_LIBSSH2            OFF CACHE BOOL "Disable libssh2 dependency" FORCE)
SET(CURL_USE_LIBSSH             OFF CACHE BOOL "Disable libssh dependency" FORCE)
SET(CURL_USE_GSASL              OFF CACHE BOOL "Disable libgsasl dependency" FORCE)
SET(CURL_USE_GSSAPI             OFF CACHE BOOL "Disable GSSAPI dependency" FORCE)
SET(CURL_USE_LIBBACKTRACE       OFF CACHE BOOL "Disable libbacktrace dependency" FORCE)
SET(CURL_USE_LIBUV              OFF CACHE BOOL "Disable libuv dependency" FORCE)
SET(CURL_ZLIB                   OFF CACHE STRING "Disable zlib dependency" FORCE)
SET(CURL_BROTLI                 OFF CACHE STRING "Disable brotli dependency" FORCE)
SET(CURL_ZSTD                   OFF CACHE STRING "Disable zstd dependency" FORCE)

SET(CURL_DISABLE_ALTSVC         ON  CACHE BOOL "Disable alt-svc support" FORCE)
SET(CURL_DISABLE_AWS            ON  CACHE BOOL "Disable aws-sigv4 support" FORCE)
SET(CURL_DISABLE_COOKIES        ON  CACHE BOOL "Disable cookies support" FORCE)
SET(CURL_DISABLE_DOH            ON  CACHE BOOL "Disable DNS-over-HTTPS support" FORCE)
SET(CURL_DISABLE_FORM_API       ON  CACHE BOOL "Disable form API support" FORCE)
SET(CURL_DISABLE_HSTS           ON  CACHE BOOL "Disable HSTS support" FORCE)
SET(CURL_DISABLE_MIME           ON  CACHE BOOL "Disable MIME support" FORCE)
SET(CURL_DISABLE_NEGOTIATE_AUTH ON  CACHE BOOL "Disable negotiate auth support" FORCE)
SET(CURL_DISABLE_PROXY          ON  CACHE BOOL "Disable proxy support" FORCE)
SET(CURL_DISABLE_SRP            ON  CACHE BOOL "Disable TLS-SRP support" FORCE)
SET(CURL_DISABLE_WEBSOCKETS     ON  CACHE BOOL "Disable WebSocket support" FORCE)
SET(CURL_ENABLE_NTLM            OFF CACHE BOOL "Disable NTLM support" FORCE)
SET(CURL_ENABLE_SMB             OFF CACHE BOOL "Disable SMB support" FORCE)
SET(ENABLE_UNIX_SOCKETS         OFF CACHE BOOL "Disable Unix domain sockets support" FORCE)

IF(WIN32)
    SET(CURL_CA_NATIVE          OFF CACHE BOOL "Use Windows native CA store when available" FORCE)
    SET(CURL_WINDOWS_SSPI       OFF CACHE BOOL "Disable Windows SSPI support" FORCE)
    SET(CURL_STATIC_CRT         OFF CACHE BOOL "Use MSVC dynamic runtime" FORCE)
ELSE()
    SET(CURL_CA_NATIVE          OFF CACHE BOOL "Use system CA bundle/path detection" FORCE)
ENDIF()

ADD_SUBDIRECTORY("${CURL_SOURCE_DIR}" "${CURL_BINARY_DIR}")

IF(NOT TARGET libcurl_shared)
    MESSAGE(FATAL_ERROR "curl shared target was not generated.")
ENDIF()

IF(NOT TARGET ${CURRENT_TARGET_NAME})
    ADD_LIBRARY(${CURRENT_TARGET_NAME} ALIAS libcurl_shared)
ENDIF()

IF(TARGET libcurl_object)
    PROJECT_TARGET_APPLY_COMMON_OPTIONS(libcurl_object)
ENDIF()
PROJECT_TARGET_APPLY_COMMON_OPTIONS(libcurl_shared)

SET_PROPERTY(TARGET libcurl_shared PROPERTY FOLDER "projects")
IF(TARGET libcurl_object)
    SET_PROPERTY(TARGET libcurl_object PROPERTY FOLDER "projects")
ENDIF()

IF(WIN32)
    SET_PROPERTY(TARGET libcurl_shared PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    SET_PROPERTY(TARGET libcurl_shared PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_DEBUGGER_WORKING_DIRECTORY}")

    IF(TARGET libcurl_object)
        SET_PROPERTY(TARGET libcurl_object PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    ENDIF()
ENDIF()
