IF(WIN32 AND CMAKE_GENERATOR MATCHES "Visual Studio")
    SET(POCO_VSPROJ_BUILD_DIR "${CMAKE_PROJECT_ROOT_DIR}/3rd/poco/.build/windows/x64-${CMAKE_BUILD_TYPE}")

    FUNCTION(GET_POCO_EXTERNAL_MSPROJECT_PATH COMPONENT_NAME OUTPUT_VARIABLE)
        IF("${COMPONENT_NAME}" STREQUAL "NetSSL")
            SET(POCO_PROJECT_PATH "NetSSL_OpenSSL/NetSSL.vcxproj")
        ELSEIF("${COMPONENT_NAME}" STREQUAL "DataSQLite")
            SET(POCO_PROJECT_PATH "Data/SQLite/DataSQLite.vcxproj")
        ELSEIF("${COMPONENT_NAME}" STREQUAL "DataMySQL")
            SET(POCO_PROJECT_PATH "Data/MySQL/DataMySQL.vcxproj")
        ELSE()
            SET(POCO_PROJECT_PATH "${COMPONENT_NAME}/${COMPONENT_NAME}.vcxproj")
        ENDIF()

        SET(${OUTPUT_VARIABLE} "${POCO_PROJECT_PATH}" PARENT_SCOPE)
    ENDFUNCTION()

    FUNCTION(ADD_POCO_EXTERNAL_MSPROJECT TARGET_NAME PROJECT_PATH)
        SET(POCO_VSPROJ "${POCO_VSPROJ_BUILD_DIR}/${PROJECT_PATH}")

        IF(EXISTS "${POCO_VSPROJ}")
            INCLUDE_EXTERNAL_MSPROJECT(
                ${TARGET_NAME}
                "${POCO_VSPROJ}"
                PLATFORM x64
            )

            SET_PROPERTY(TARGET ${TARGET_NAME} PROPERTY FOLDER "poco")
        ELSE()
            MESSAGE(WARNING
                "Poco vcxproj not found: ${POCO_VSPROJ}. "
                "Run 3rd/build.poco.bat ${CMAKE_BUILD_TYPE} before generating the main Visual Studio solution."
            )
        ENDIF()
    ENDFUNCTION()

    FOREACH(POCO_COMPONENT ${POCO_COMPONENTS})
        GET_POCO_EXTERNAL_MSPROJECT_PATH("${POCO_COMPONENT}" POCO_PROJECT_PATH)
        ADD_POCO_EXTERNAL_MSPROJECT("Poco${POCO_COMPONENT}" "${POCO_PROJECT_PATH}")
    ENDFOREACH()
ENDIF()
