set(MIMALLOC_PRESET_ROOT "${CMAKE_CURRENT_LIST_DIR}/mimalloc" CACHE PATH "mimalloc preset root" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(MIMALLOC_USE_CXX ON)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(MIMALLOC_USE_CXX OFF)
else()
    message(FATAL_ERROR "Unsupported host platform for mimalloc.cmake: ${CMAKE_HOST_SYSTEM_NAME}")
endif()

set(CMAKE_MODULE_PATH "${MIMALLOC_PRESET_ROOT}/cmake" CACHE STRING "CMake module path" FORCE)

# Language standards
set(CMAKE_C_STANDARD 11 CACHE STRING "C standard" FORCE)
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C standard" FORCE)
set(CMAKE_C_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C extensions" FORCE)
set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C++ standard" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C++ extensions" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    foreach(MIMALLOC_FLAG_VAR CMAKE_C_FLAGS CMAKE_CXX_FLAGS)
        set(MIMALLOC_FLAGS "${${MIMALLOC_FLAG_VAR}}")
        if(NOT MIMALLOC_FLAGS MATCHES "(^| )/MP( |$)")
            string(APPEND MIMALLOC_FLAGS " /MP")
        endif()
        if(NOT MIMALLOC_FLAGS MATCHES "(^| )/utf-8( |$)")
            string(APPEND MIMALLOC_FLAGS " /utf-8")
        endif()
        if(NOT MIMALLOC_FLAGS MATCHES "(^| )/wd4819( |$)")
            string(APPEND MIMALLOC_FLAGS " /wd4819")
        endif()
        set(${MIMALLOC_FLAG_VAR} "${MIMALLOC_FLAGS}" CACHE STRING "MSVC compiler flags" FORCE)
    endforeach()

    set(MIMALLOC_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    if(NOT MIMALLOC_CXX_FLAGS MATCHES "(^| )/EHsc( |$)")
        string(APPEND MIMALLOC_CXX_FLAGS " /EHsc")
    endif()
    set(CMAKE_CXX_FLAGS "${MIMALLOC_CXX_FLAGS}" CACHE STRING "MSVC C++ compiler flags" FORCE)
endif()

# Core build behavior
set(MIMALLOC_OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin" CACHE PATH "mimalloc build output directory" FORCE)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${MIMALLOC_OUTPUT_DIR}" CACHE PATH "Runtime output" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${MIMALLOC_OUTPUT_DIR}" CACHE PATH "Library output" FORCE)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${MIMALLOC_OUTPUT_DIR}" CACHE PATH "Archive output" FORCE)
foreach(MIMALLOC_OUTPUT_CONFIG Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${MIMALLOC_OUTPUT_CONFIG}" MIMALLOC_OUTPUT_CONFIG_UPPER)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${MIMALLOC_OUTPUT_CONFIG_UPPER} "${MIMALLOC_OUTPUT_DIR}" CACHE PATH "Runtime output for ${MIMALLOC_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${MIMALLOC_OUTPUT_CONFIG_UPPER} "${MIMALLOC_OUTPUT_DIR}" CACHE PATH "Library output for ${MIMALLOC_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${MIMALLOC_OUTPUT_CONFIG_UPPER} "${MIMALLOC_OUTPUT_DIR}" CACHE PATH "Archive output for ${MIMALLOC_OUTPUT_CONFIG}" FORCE)
endforeach()

# Core build options
set(MI_BUILD_SHARED ON CACHE BOOL "Build shared library" FORCE)
set(MI_BUILD_STATIC OFF CACHE BOOL "Build static library" FORCE)
set(MI_BUILD_OBJECT OFF CACHE BOOL "Build object library" FORCE)
set(MI_BUILD_TESTS OFF CACHE BOOL "Build test executables" FORCE)

set(MI_OVERRIDE ON CACHE BOOL "Override the standard malloc interface" FORCE)
set(MI_WIN_REDIRECT ON CACHE BOOL "Use redirection module on Windows" FORCE)

# Disabled mimalloc features
set(MI_SECURE OFF CACHE BOOL "Use security mitigations" FORCE)
set(MI_SECURE_FULL OFF CACHE BOOL "Use full security mitigations" FORCE)
set(MI_PADDING OFF CACHE BOOL "Enable padding to detect heap block overflow" FORCE)
set(MI_XMALLOC OFF CACHE BOOL "Abort on memory allocation failure" FORCE)
set(MI_SHOW_ERRORS OFF CACHE BOOL "Show error and warning messages by default" FORCE)
set(MI_GUARDED OFF CACHE BOOL "Build with guard pages behind certain allocations" FORCE)
set(MI_OPT_ARCH OFF CACHE BOOL "Enable architecture-specific optimizations" FORCE)
set(MI_SEE_ASM OFF CACHE BOOL "Generate assembly files" FORCE)

if(MIMALLOC_USE_CXX)
    set(MI_USE_CXX ON CACHE BOOL "Use the C++ compiler to compile mimalloc" FORCE)
    set(MI_NO_USE_CXX OFF CACHE BOOL "Do not force plain C compilation" FORCE)
else()
    set(MI_USE_CXX OFF CACHE BOOL "Use the C++ compiler to compile mimalloc" FORCE)
    set(MI_NO_USE_CXX ON CACHE BOOL "Force plain C compilation" FORCE)
endif()
