set(POCO_PRESET_ROOT "${CMAKE_CURRENT_LIST_DIR}/poco" CACHE PATH "Poco preset root" FORCE)
set(POCO_THIRD_DIR "${POCO_PRESET_ROOT}/../../../3rd-libs" CACHE PATH "Poco third-party dependency root" FORCE)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(POCO_PLATFORM_DIR "windows")
    set(POCO_3RD_PLATFORM_DIR "x64-windows")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(POCO_PLATFORM_DIR "linux")
    set(POCO_3RD_PLATFORM_DIR "x64-ubuntu-24.04")
else()
    message(FATAL_ERROR "Unsupported host platform for poco.cmake: ${CMAKE_HOST_SYSTEM_NAME}")
endif()
set(POCO_CMAKE_OVERRIDE_DIR "${POCO_PRESET_ROOT}/.build/${POCO_PLATFORM_DIR}/cmake-overrides" CACHE PATH "Poco CMake override directory" FORCE)

# Force Poco's C++20 probe to fail so the upstream CMakeLists uses its C++17 fallback.
file(MAKE_DIRECTORY "${POCO_CMAKE_OVERRIDE_DIR}")
file(WRITE "${POCO_CMAKE_OVERRIDE_DIR}/CXX2x.cmake" [=[
function(check_for_cxx20_compiler _VAR)
    message(STATUS "Checking for C++20 compiler - disabled by poco.cmake")
    set(${_VAR} OFF PARENT_SCOPE)
endfunction()
]=])

set(CMAKE_MODULE_PATH "${POCO_CMAKE_OVERRIDE_DIR}" CACHE STRING "CMake module path" FORCE)

# Language standards
set(CMAKE_C_STANDARD 11 CACHE STRING "C standard" FORCE)
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C standard" FORCE)
set(CMAKE_C_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C extensions" FORCE)
set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ standard" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C++ standard" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C++ extensions" FORCE)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    foreach(POCO_FLAG_VAR CMAKE_C_FLAGS CMAKE_CXX_FLAGS)
        set(POCO_FLAGS "${${POCO_FLAG_VAR}}")
        if(NOT POCO_FLAGS MATCHES "(^| )/MP( |$)")
            string(APPEND POCO_FLAGS " /MP")
        endif()
        if(NOT POCO_FLAGS MATCHES "(^| )/utf-8( |$)")
            string(APPEND POCO_FLAGS " /utf-8")
        endif()
        if(NOT POCO_FLAGS MATCHES "(^| )/wd4819( |$)")
            string(APPEND POCO_FLAGS " /wd4819")
        endif()
        set(${POCO_FLAG_VAR} "${POCO_FLAGS}" CACHE STRING "MSVC compiler flags" FORCE)
    endforeach()

    set(POCO_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    if(NOT POCO_CXX_FLAGS MATCHES "(^| )/EHsc( |$)")
        string(APPEND POCO_CXX_FLAGS " /EHsc")
    endif()
    set(CMAKE_CXX_FLAGS "${POCO_CXX_FLAGS}" CACHE STRING "MSVC C++ compiler flags" FORCE)
endif()

# Core build behavior
set(POCO_OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin" CACHE PATH "Poco build output directory" FORCE)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${POCO_OUTPUT_DIR}" CACHE PATH "Runtime output" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${POCO_OUTPUT_DIR}" CACHE PATH "Library output" FORCE)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${POCO_OUTPUT_DIR}" CACHE PATH "Archive output" FORCE)
foreach(POCO_OUTPUT_CONFIG Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${POCO_OUTPUT_CONFIG}" POCO_OUTPUT_CONFIG_UPPER)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${POCO_OUTPUT_CONFIG_UPPER} "${POCO_OUTPUT_DIR}" CACHE PATH "Runtime output for ${POCO_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${POCO_OUTPUT_CONFIG_UPPER} "${POCO_OUTPUT_DIR}" CACHE PATH "Library output for ${POCO_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${POCO_OUTPUT_CONFIG_UPPER} "${POCO_OUTPUT_DIR}" CACHE PATH "Archive output for ${POCO_OUTPUT_CONFIG}" FORCE)
endforeach()

function(poco_copy_runtime_dependency POCO_RUNTIME_SOURCE)
    if(ARGC GREATER 1)
        set(POCO_RUNTIME_NAME "${ARGV1}")
    else()
        get_filename_component(POCO_RUNTIME_NAME "${POCO_RUNTIME_SOURCE}" NAME)
    endif()

    if(NOT EXISTS "${POCO_RUNTIME_SOURCE}")
        message(FATAL_ERROR "Missing Poco runtime dependency: ${POCO_RUNTIME_SOURCE}")
    endif()

    file(MAKE_DIRECTORY "${POCO_OUTPUT_DIR}")
    file(COPY_FILE "${POCO_RUNTIME_SOURCE}" "${POCO_OUTPUT_DIR}/${POCO_RUNTIME_NAME}" ONLY_IF_DIFFERENT)
endfunction()

set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries" FORCE)
set(POCO_MINIMAL_BUILD ON CACHE BOOL "Build only explicitly enabled Poco components" FORCE)
set(POCO_MT OFF CACHE BOOL "Use /MT runtime" FORCE)
set(POCO_UNBUNDLED OFF CACHE BOOL "Use external bundled dependencies" FORCE)
set(POCO_SQLITE_UNBUNDLED OFF CACHE BOOL "Use external SQLite" FORCE)
set(POCO_DATA_NO_SQL_PARSER OFF CACHE BOOL "Disable SQL parser" FORCE)
set(POCO_SOO ON CACHE BOOL "Enable small object optimization in Poco::Foundation" FORCE)
set(POCO_NO_FORK_EXEC OFF CACHE BOOL "Disable fork() and exec*()" FORCE)
set(POCO_ENABLE_STD_MUTEX OFF CACHE BOOL "Use std::mutex implementation" FORCE)

# Enabled Poco modules and features
set(ENABLE_FOUNDATION ON CACHE BOOL "Enable Foundation" FORCE)
set(ENABLE_CPPUNIT ON CACHE BOOL "Enable CppUnit" FORCE)
set(ENABLE_ENCODINGS ON CACHE BOOL "Enable Encodings" FORCE)
set(ENABLE_XML ON CACHE BOOL "Enable XML" FORCE)
set(ENABLE_JSON ON CACHE BOOL "Enable JSON" FORCE)
set(ENABLE_UTIL ON CACHE BOOL "Enable Util" FORCE)
set(ENABLE_NET ON CACHE BOOL "Enable Net" FORCE)
set(ENABLE_REDIS ON CACHE BOOL "Enable Redis" FORCE)
set(ENABLE_JWT ON CACHE BOOL "Enable JWT" FORCE)
set(ENABLE_FASTLOGGER ON CACHE BOOL "Enable FastLogger" FORCE)
set(ENABLE_NETSSL ON CACHE BOOL "Enable NetSSL OpenSSL" FORCE)
set(ENABLE_CRYPTO ON CACHE BOOL "Enable Crypto" FORCE)
set(ENABLE_DATA ON CACHE BOOL "Enable Data" FORCE)
set(ENABLE_DATA_SQLITE ON CACHE BOOL "Enable Data SQLite" FORCE)
set(ENABLE_DATA_MYSQL ON CACHE BOOL "Enable Data MySQL" FORCE)
set(ENABLE_PROMETHEUS ON CACHE BOOL "Enable Prometheus" FORCE)
set(ENABLE_ZIP ON CACHE BOOL "Enable Zip" FORCE)
set(ENABLE_TESTS ON CACHE BOOL "Enable tests" FORCE)

# Disabled Poco modules and features
set(POCO_ENABLE_CPP20 OFF CACHE BOOL "Disable C++20-only Poco options" FORCE)
set(ENABLE_TRACE OFF CACHE BOOL "Disable stack tracing for strict C++17 builds" FORCE)
set(ENABLE_TEST_DEPRECATED OFF CACHE BOOL "Disable deprecated tests" FORCE)
set(ENABLE_INSTALL_CPPUNIT OFF CACHE BOOL "Disable CppUnit installation" FORCE)
set(ENABLE_SAMPLES OFF CACHE BOOL "Disable samples" FORCE)
set(ENABLE_FUZZING OFF CACHE BOOL "Disable fuzzing targets" FORCE)
set(ENABLE_COMPILER_WARNINGS OFF CACHE BOOL "Disable maintainer compiler warnings" FORCE)
set(ENABLE_BENCHMARK OFF CACHE BOOL "Disable Benchmark" FORCE)
set(ENABLE_MONGODB OFF CACHE BOOL "Disable MongoDB" FORCE)
set(ENABLE_DNSSD OFF CACHE BOOL "Disable DNSSD" FORCE)
set(ENABLE_DNSSD_DEFAULT OFF CACHE BOOL "Disable default DNSSD implementation" FORCE)
set(ENABLE_DNSSD_AVAHI OFF CACHE BOOL "Disable DNSSD Avahi" FORCE)
set(ENABLE_DNSSD_BONJOUR OFF CACHE BOOL "Disable DNSSD Bonjour" FORCE)
set(ENABLE_PDF OFF CACHE BOOL "Disable PDF" FORCE)
set(ENABLE_NETSSL_WIN OFF CACHE BOOL "Disable NetSSL Windows" FORCE)
set(ENABLE_DATA_POSTGRESQL OFF CACHE BOOL "Disable Data PostgreSQL" FORCE)
set(ENABLE_DATA_ODBC OFF CACHE BOOL "Disable Data ODBC" FORCE)
set(ENABLE_DATA_SQL_SERVER_BIG_STRINGS OFF CACHE BOOL "Disable SQL Server big strings" FORCE)
set(ENABLE_SEVENZIP OFF CACHE BOOL "Disable SevenZip" FORCE)
set(ENABLE_ACTIVERECORD OFF CACHE BOOL "Disable ActiveRecord" FORCE)
set(ENABLE_ACTIVERECORD_COMPILER OFF CACHE BOOL "Disable ActiveRecord compiler" FORCE)
set(ENABLE_APACHECONNECTOR OFF CACHE BOOL "Disable ApacheConnector" FORCE)
set(ENABLE_CPPPARSER OFF CACHE BOOL "Disable CppParser" FORCE)
set(ENABLE_POCODOC OFF CACHE BOOL "Disable PocoDoc" FORCE)
set(ENABLE_PAGECOMPILER OFF CACHE BOOL "Disable PageCompiler" FORCE)
set(ENABLE_PAGECOMPILER_FILE2PAGE OFF CACHE BOOL "Disable File2Page" FORCE)
set(ENABLE_ENCODINGS_COMPILER OFF CACHE BOOL "Disable Encodings compiler" FORCE)
set(ENABLE_MODULES OFF CACHE BOOL "Disable C++ modules" FORCE)

# External dependencies
set(OPENSSL_ROOT_DIR "${POCO_THIRD_DIR}/openssl-1.1.1t/${POCO_3RD_PLATFORM_DIR}" CACHE PATH "OpenSSL root" FORCE)
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include" CACHE PATH "OpenSSL include directory" FORCE)
set(MYSQL_ROOT_DIR "${POCO_THIRD_DIR}/mysql-8.0.33/${POCO_3RD_PLATFORM_DIR}" CACHE PATH "MySQL root" FORCE)
set(MYSQL_INCLUDE_DIR "${MYSQL_ROOT_DIR}/include" CACHE PATH "MySQL include directory" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libssl.lib" CACHE FILEPATH "OpenSSL SSL library" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libcrypto.lib" CACHE FILEPATH "OpenSSL Crypto library" FORCE)
    set(MYSQL_LIBRARY "${MYSQL_ROOT_DIR}/lib/libmysql.lib" CACHE FILEPATH "MySQL client library" FORCE)
    poco_copy_runtime_dependency("${OPENSSL_ROOT_DIR}/lib/libssl-1_1-x64.dll")
    poco_copy_runtime_dependency("${OPENSSL_ROOT_DIR}/lib/libcrypto-1_1-x64.dll")
    poco_copy_runtime_dependency("${MYSQL_ROOT_DIR}/lib/libmysql.dll")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libssl.so.1.1" CACHE FILEPATH "OpenSSL SSL library" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libcrypto.so.1.1" CACHE FILEPATH "OpenSSL Crypto library" FORCE)
    set(MYSQL_LIBRARY "${MYSQL_ROOT_DIR}/lib/libmysqlclient.so.21.2.33" CACHE FILEPATH "MySQL client library" FORCE)
    poco_copy_runtime_dependency("${OPENSSL_SSL_LIBRARY}")
    poco_copy_runtime_dependency("${OPENSSL_CRYPTO_LIBRARY}")
    poco_copy_runtime_dependency("${MYSQL_LIBRARY}" "libmysqlclient.so.21")
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON CACHE BOOL "Use install RPATH for build-tree binaries" FORCE)
    set(CMAKE_BUILD_RPATH "$ORIGIN" CACHE STRING "Build-tree runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH "$ORIGIN" CACHE STRING "Install runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH_USE_LINK_PATH OFF CACHE BOOL "Do not append link paths to install RPATH" FORCE)
    foreach(POCO_LINKER_FLAG_VAR CMAKE_SHARED_LINKER_FLAGS CMAKE_EXE_LINKER_FLAGS)
        set(POCO_LINKER_FLAGS "${${POCO_LINKER_FLAG_VAR}}")
        foreach(POCO_RPATH_LINK_DIR "${OPENSSL_ROOT_DIR}/lib" "${MYSQL_ROOT_DIR}/lib")
            set(POCO_RPATH_LINK_FLAG "-Wl,-rpath-link,${POCO_RPATH_LINK_DIR}")
            string(FIND "${POCO_LINKER_FLAGS}" "${POCO_RPATH_LINK_FLAG}" POCO_RPATH_LINK_FOUND)
            if(POCO_RPATH_LINK_FOUND EQUAL -1)
                string(APPEND POCO_LINKER_FLAGS " ${POCO_RPATH_LINK_FLAG}")
            endif()
        endforeach()
        set(${POCO_LINKER_FLAG_VAR} "${POCO_LINKER_FLAGS}" CACHE STRING "Linux linker flags" FORCE)
    endforeach()
endif()
