# Generated by Django 5.2.12 on 2026-04-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0003_alter_userprofile_role_usercommandpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleCommandPermission',
        ),
    ]
