# Generated by Django 5.2.12 on 2026-06-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0003_gmcommand_constraints_and_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_username', models.CharField(blank=True, default='', max_length=150, verbose_name='操作用户名')),
                ('action', models.CharField(choices=[('create', '发布'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('announcement_type', models.CharField(max_length=10, verbose_name='公告类型')),
                ('announcement_id', models.CharField(blank=True, default='', max_length=64, verbose_name='公告ID')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='响应数据')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name='原始响应')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '公告日志',
                'verbose_name_plural': '公告日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='annlog_created_idx'), models.Index(fields=['user', '-created_at'], name='annlog_user_created_idx'), models.Index(fields=['status', '-created_at'], name='annlog_status_created_idx'), models.Index(fields=['action', '-created_at'], name='annlog_action_created_idx'), models.Index(fields=['platform', 'channel', '-created_at'], name='annlog_plat_chan_ct_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户公告权限',
                'verbose_name_plural': '用户公告权限',
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_user_announcement_permission')],
            },
        ),
    ]
