# Generated by Django 5.2.12 on 2026-04-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0004_remove_rolecommandpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='request_content',
            field=models.TextField(blank=True, default='', help_text='IDIP协议完整请求内容', verbose_name='完整请求JSON'),
        ),
    ]
