# Generated by Django 5.2.12 on 2026-06-26 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0004_announcementlog_userannouncementpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已作废'), ('failed', '发布失败')], default='pending', max_length=20, verbose_name='审核状态')),
                ('submitter_username', models.CharField(blank=True, default='', max_length=150, verbose_name='提交用户名')),
                ('reviewer_username', models.CharField(blank=True, default='', max_length=150, verbose_name='审核用户名')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('announcement_type', models.CharField(choices=[('1', '周更新公告'), ('2', '常驻公告'), ('3', '轮播图')], max_length=10, verbose_name='公告类型')),
                ('announcement_id', models.CharField(blank=True, default='-1', max_length=64, verbose_name='公告ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='公告正文')),
                ('priority', models.IntegerField(default=0, verbose_name='显示优先级')),
                ('image_1', models.CharField(blank=True, default='', max_length=500, verbose_name='Image_1')),
                ('image_link_1', models.CharField(blank=True, default='', max_length=500, verbose_name='ImageLink_1')),
                ('image_2', models.CharField(blank=True, default='', max_length=500, verbose_name='Image_2')),
                ('image_link_2', models.CharField(blank=True, default='', max_length=500, verbose_name='ImageLink_2')),
                ('image_3', models.CharField(blank=True, default='', max_length=500, verbose_name='Image_3')),
                ('image_link_3', models.CharField(blank=True, default='', max_length=500, verbose_name='ImageLink_3')),
                ('reserve_1', models.TextField(blank=True, default='', verbose_name='Reserve_1')),
                ('reserve_2', models.TextField(blank=True, default='', verbose_name='Reserve_2')),
                ('payload', models.JSONField(default=dict, verbose_name='待发布数据')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('remote_response', models.JSONField(blank=True, null=True, verbose_name='远端响应')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name='远端原始响应')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_announcement_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_announcement_reviews', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '公告审核',
                'verbose_name_plural': '公告审核',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='annrev_status_created_idx'), models.Index(fields=['submitter', '-created_at'], name='annrev_submit_created_idx'), models.Index(fields=['reviewer', '-reviewed_at'], name='annrev_reviewed_idx'), models.Index(fields=['platform', 'channel', 'status'], name='annrev_plat_chan_stat_idx'), models.Index(fields=['announcement_type', 'status'], name='annrev_type_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('announcement_type', '1'), ('status', 'pending')), fields=('platform', 'channel', 'announcement_type'), name='uniq_pending_weekly_review')],
            },
        ),
    ]
