# Generated by Django 5.2.12 on 2026-04-12 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0005_add_request_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercommandpermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gmtool.gmcommand', verbose_name='命令'),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='username',
            field=models.CharField(max_length=150, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gmtool.role', verbose_name='角色'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['user', '-created_at'], name='cmdlog_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['status', '-created_at'], name='cmdlog_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['command', '-created_at'], name='cmdlog_cmd_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gmcommand',
            index=models.Index(fields=['command_id'], name='gmcmd_cmdid_idx'),
        ),
        migrations.AddIndex(
            model_name='gmcommand',
            index=models.Index(fields=['is_active', 'command_id'], name='gmcmd_active_cmd_idx'),
        ),
        migrations.AddIndex(
            model_name='gmcommand',
            index=models.Index(fields=['request_id'], name='gmcmd_reqid_idx'),
        ),
        migrations.AddIndex(
            model_name='gmcommand',
            index=models.Index(fields=['response_id'], name='gmcmd_respid_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['action', '-created_at'], name='loginlog_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['username', '-created_at'], name='loginlog_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercommandpermission',
            constraint=models.UniqueConstraint(fields=('user', 'command'), name='uniq_user_command_permission'),
        ),
    ]
