# Generated by Django 5.2.12 on 2026-06-26 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0005_announcementreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('mail', '邮件审核'), ('marquee', '走马灯审核')], max_length=20, verbose_name='审核类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已作废'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='审核状态')),
                ('command_code', models.CharField(max_length=20, verbose_name='命令编号')),
                ('command_name', models.CharField(max_length=200, verbose_name='命令名称')),
                ('command_tab', models.CharField(blank=True, default='', max_length=200, verbose_name='分组标签')),
                ('request_name', models.CharField(max_length=100, verbose_name='请求名')),
                ('request_id', models.IntegerField(verbose_name='协议请求ID')),
                ('response_name', models.CharField(max_length=100, verbose_name='响应名')),
                ('response_id', models.IntegerField(verbose_name='协议响应ID')),
                ('submitter_username', models.CharField(blank=True, default='', max_length=150, verbose_name='提交用户名')),
                ('reviewer_username', models.CharField(blank=True, default='', max_length=150, verbose_name='审核用户名')),
                ('partition', models.IntegerField(default=0, verbose_name='服务器组号')),
                ('params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('request_content', models.TextField(blank=True, default='', verbose_name='完整请求JSON')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='响应数据')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_reviews', to='gmtool.gmcommand', verbose_name='命令')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_command_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_command_reviews', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '命令审核',
                'verbose_name_plural': '命令审核',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_type', 'status', '-created_at'], name='cmdrev_type_status_ct_idx'), models.Index(fields=['submitter', '-created_at'], name='cmdrev_submit_ct_idx'), models.Index(fields=['reviewer', '-reviewed_at'], name='cmdrev_reviewed_idx'), models.Index(fields=['command_code', '-created_at'], name='cmdrev_cmd_ct_idx')],
            },
        ),
    ]
