# Generated by Django 5.2.12 on 2026-04-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0006_alter_usercommandpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmcommand',
            name='field_labels',
            field=models.JSONField(default=dict, help_text='所有字段（含嵌套结构体）的 id -> name 映射，用于结果展示', verbose_name='字段标签映射'),
        ),
    ]
