# Generated by Django 5.2.12 on 2026-06-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0006_commandreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementreview',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('processing', '发布中'), ('approved', '已通过'), ('rejected', '已作废'), ('failed', '发布失败')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='commandreview',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('processing', '执行中'), ('approved', '已通过'), ('rejected', '已作废'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
