# Generated by Django 5.2.12 on 2026-04-14 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtool', '0007_add_field_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['-created_at'], name='cmdlog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['-created_at'], name='loginlog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='loginlog_ip_created_idx'),
        ),
    ]
