# 项目名字
PROJECT(spdlog)

# 头文件目录
SET(CURRENT_INCLUDE_DIR
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/fmt/include
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include
)

# 宏定义、编译选项、链接库
IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        -Dspdlog_EXPORTS
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        -DSPDLOG_FMT_EXTERNAL
        -DSPDLOG_COMPILED_LIB
        -DSPDLOG_SHARED_LIB
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        /wd4275
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        fmt
    )
ELSE()
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        -Dspdlog_EXPORTS
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        -DSPDLOG_FMT_EXTERNAL
        -DSPDLOG_COMPILED_LIB
        -DSPDLOG_SHARED_LIB
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        fmt
    )
ENDIF()

# 头文件
FILE(GLOB_RECURSE CURRENT_DIR_INCLUDE_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include/*.h
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include/*.hpp
)

# 源文件
SET(CURRENT_DIR_SRC_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/cfg.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/async.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/spdlog.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/file_sinks.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/color_sinks.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/stdout_sinks.cpp
)

# 生成动态库
ADD_LIBRARY(${PROJECT_NAME}                SHARED  ${CURRENT_DIR_INCLUDE_LIST} ${CURRENT_DIR_SRC_LIST})
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME} PRIVATE ${CURRENT_INCLUDE_DIR})
TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE ${CURRENT_PRIVATE_COMPILE_DEFINITIONS})
TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PUBLIC  ${CURRENT_PUBLIC_COMPILE_DEFINITIONS})
TARGET_COMPILE_OPTIONS(${PROJECT_NAME}     PRIVATE ${CURRENT_COMPILE_OPTIONS})
TARGET_LINK_DIRECTORIES(${PROJECT_NAME}    PRIVATE ${CMAKE_PROJECT_BUILD_ROOT_DIR}/${CMAKE_BUILD_TYPE})
TARGET_LINK_LIBRARIES(${PROJECT_NAME}      PUBLIC  ${CURRENT_LINK_LIBS})

# 其它设置
IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    # MSVC运行库设置
    SET_PROPERTY(TARGET ${PROJECT_NAME} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")

    # VS工程设置
    SET_PROPERTY(TARGET ${PROJECT_NAME} PROPERTY FOLDER "3rd")

    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include PREFIX "include"
        FILES ${CURRENT_DIR_INCLUDE_LIST})
    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src PREFIX "src"
        FILES ${CURRENT_DIR_SRC_LIST})
ENDIF()