# 项目名字
PROJECT(spdlog)

# 头文件目录
SET(CURRENT_INCLUDE_DIR
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/fmt/include
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include
)

# 宏定义、编译选项
IF(MSVC)
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        # ...
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        -DSPDLOG_FMT_EXTERNAL
        -DSPDLOG_COMPILED_LIB
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )
ELSE()
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        # ...
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        -DSPDLOG_FMT_EXTERNAL
        -DSPDLOG_COMPILED_LIB
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        # ...
    )
ENDIF()

# 头文件
FILE(GLOB_RECURSE CURRENT_DIR_INCLUDE_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include/*.h
)

# 源文件
SET(CURRENT_DIR_SRC_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/cfg.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/async.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/spdlog.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/file_sinks.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/color_sinks.cpp
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/src/stdout_sinks.cpp
)

# 生成静态库
ADD_LIBRARY(${PROJECT_NAME}                STATIC  ${CURRENT_DIR_INCLUDE_LIST} ${CURRENT_DIR_SRC_LIST})
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME} PRIVATE ${CURRENT_INCLUDE_DIR})
TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE ${CURRENT_PRIVATE_COMPILE_DEFINITIONS})
TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PUBLIC  ${CURRENT_PUBLIC_COMPILE_DEFINITIONS})
TARGET_COMPILE_OPTIONS(${PROJECT_NAME}     PRIVATE ${CURRENT_COMPILE_OPTIONS})
TARGET_LINK_LIBRARIES(${PROJECT_NAME}      PUBLIC  fmt)

# 生成VS工程目录
IF(MSVC)
    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/spdlog/include PREFIX "include"
        FILES ${CURRENT_DIR_INCLUDE_LIST})
    SOURCE_GROUP("src"
        FILES ${CURRENT_DIR_SRC_LIST})
ENDIF()