set(CURL_PRESET_ROOT "${CMAKE_CURRENT_LIST_DIR}/../curl"     CACHE PATH "curl preset root" FORCE)
set(CURL_THIRD_DIR   "${CURL_PRESET_ROOT}/../../../3rd-libs" CACHE PATH "curl third-party dependency root" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(CURL_PLATFORM_DIR "windows")
    set(CURL_3RD_PLATFORM_DIR "x64-windows")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(CURL_PLATFORM_DIR "linux")
    set(CURL_3RD_PLATFORM_DIR "x64-ubuntu-24.04")
else()
    message(FATAL_ERROR "Unsupported host platform for curl.cmake: ${CMAKE_HOST_SYSTEM_NAME}")
endif()

# Language standards
set(CMAKE_C_STANDARD 11 CACHE STRING "C standard" FORCE)
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C standard" FORCE)
set(CMAKE_C_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C extensions" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    foreach(CURL_FLAG_VAR CMAKE_C_FLAGS CMAKE_CXX_FLAGS)
        set(CURL_FLAGS "${${CURL_FLAG_VAR}}")
        if(NOT CURL_FLAGS MATCHES "(^| )/MP( |$)")
            string(APPEND CURL_FLAGS " /MP")
        endif()
        if(NOT CURL_FLAGS MATCHES "(^| )/utf-8( |$)")
            string(APPEND CURL_FLAGS " /utf-8")
        endif()
        if(NOT CURL_FLAGS MATCHES "(^| )/wd4819( |$)")
            string(APPEND CURL_FLAGS " /wd4819")
        endif()
        set(${CURL_FLAG_VAR} "${CURL_FLAGS}" CACHE STRING "MSVC compiler flags" FORCE)
    endforeach()

    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL" CACHE STRING "MSVC runtime library" FORCE)
endif()

# Core build behavior
set(CURL_OUTPUT_DIR                "${CMAKE_BINARY_DIR}/bin" CACHE PATH "curl build output directory" FORCE)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CURL_OUTPUT_DIR}"      CACHE PATH "Runtime output" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CURL_OUTPUT_DIR}"      CACHE PATH "Library output" FORCE)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CURL_OUTPUT_DIR}"      CACHE PATH "Archive output" FORCE)

foreach(CURL_OUTPUT_CONFIG Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${CURL_OUTPUT_CONFIG}" CURL_OUTPUT_CONFIG_UPPER)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CURL_OUTPUT_CONFIG_UPPER} "${CURL_OUTPUT_DIR}" CACHE PATH "Runtime output for ${CURL_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CURL_OUTPUT_CONFIG_UPPER} "${CURL_OUTPUT_DIR}" CACHE PATH "Library output for ${CURL_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CURL_OUTPUT_CONFIG_UPPER} "${CURL_OUTPUT_DIR}" CACHE PATH "Archive output for ${CURL_OUTPUT_CONFIG}" FORCE)
endforeach()

function(curl_copy_runtime_dependency CURL_RUNTIME_SOURCE)
    if(ARGC GREATER 1)
        set(CURL_RUNTIME_NAME "${ARGV1}")
    else()
        get_filename_component(CURL_RUNTIME_NAME "${CURL_RUNTIME_SOURCE}" NAME)
    endif()

    if(NOT EXISTS "${CURL_RUNTIME_SOURCE}")
        message(FATAL_ERROR "Missing curl runtime dependency: ${CURL_RUNTIME_SOURCE}")
    endif()

    file(MAKE_DIRECTORY "${CURL_OUTPUT_DIR}")
    file(COPY_FILE "${CURL_RUNTIME_SOURCE}" "${CURL_OUTPUT_DIR}/${CURL_RUNTIME_NAME}" ONLY_IF_DIFFERENT)
endfunction()

# Build a single shared libcurl artifact named "curl".
set(BUILD_SHARED_LIBS         ON  CACHE BOOL "Build shared libraries" FORCE)
set(BUILD_STATIC_LIBS         OFF CACHE BOOL "Build static libraries" FORCE)
set(BUILD_STATIC_CURL         OFF CACHE BOOL "Build curl executable with static libcurl" FORCE)
set(BUILD_CURL_EXE            OFF CACHE BOOL "Build curl executable" FORCE)
set(BUILD_TESTING             OFF CACHE BOOL "Build tests" FORCE)
set(BUILD_EXAMPLES            OFF CACHE BOOL "Build libcurl examples" FORCE)
set(BUILD_LIBCURL_DOCS        OFF CACHE BOOL "Build libcurl man pages" FORCE)
set(BUILD_MISC_DOCS           OFF CACHE BOOL "Build misc man pages" FORCE)
set(ENABLE_CURL_MANUAL        OFF CACHE BOOL "Build curl manual" FORCE)
set(CURL_DISABLE_INSTALL      ON  CACHE BOOL "Disable installation targets" FORCE)
set(CURL_ENABLE_EXPORT_TARGET OFF CACHE BOOL "Disable CMake export target" FORCE)
set(CURL_USE_CMAKECONFIG      OFF CACHE BOOL "Disable CMake package auto-detection" FORCE)
set(CURL_USE_PKGCONFIG        OFF CACHE BOOL "Disable pkg-config dependency detection" FORCE)

set(CMAKE_DEBUG_POSTFIX "" CACHE STRING "Do not suffix Debug artifacts" FORCE)
set(IMPORT_LIB_SUFFIX   "" CACHE STRING "Do not suffix Windows import libraries" FORCE)

# Required protocol stack: async HTTP/HTTPS and WebSocket over OpenSSL.
set(CURL_ENABLE_SSL                       ON  CACHE BOOL "Enable SSL support" FORCE)
set(CURL_USE_OPENSSL                      ON  CACHE BOOL "Enable OpenSSL for SSL/TLS" FORCE)
set(CURL_USE_SCHANNEL                     OFF CACHE BOOL "Disable Windows Schannel TLS backend" FORCE)
set(CURL_USE_MBEDTLS                      OFF CACHE BOOL "Disable mbedTLS backend" FORCE)
set(CURL_USE_WOLFSSL                      OFF CACHE BOOL "Disable wolfSSL backend" FORCE)
set(CURL_USE_GNUTLS                       OFF CACHE BOOL "Disable GnuTLS backend" FORCE)
set(CURL_USE_RUSTLS                       OFF CACHE BOOL "Disable Rustls backend" FORCE)
set(CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG OFF CACHE BOOL "Allow OpenSSL configuration loading" FORCE)

set(ENABLE_ARES              OFF CACHE BOOL "Disable c-ares support" FORCE)
set(ENABLE_THREADED_RESOLVER ON  CACHE BOOL "Enable threaded DNS lookup" FORCE)

set(CURL_DISABLE_HTTP        OFF CACHE BOOL "Enable HTTP support" FORCE)
set(CURL_DISABLE_WEBSOCKETS  OFF CACHE BOOL "Enable WebSocket support" FORCE)

# Disabled protocols.
set(CURL_DISABLE_DICT   ON CACHE BOOL "Disable DICT" FORCE)
set(CURL_DISABLE_FILE   ON CACHE BOOL "Disable FILE" FORCE)
set(CURL_DISABLE_FTP    ON CACHE BOOL "Disable FTP" FORCE)
set(CURL_DISABLE_GOPHER ON CACHE BOOL "Disable Gopher" FORCE)
set(CURL_DISABLE_IMAP   ON CACHE BOOL "Disable IMAP" FORCE)
set(CURL_DISABLE_LDAP   ON CACHE BOOL "Disable LDAP" FORCE)
set(CURL_DISABLE_LDAPS  ON CACHE BOOL "Disable LDAPS" FORCE)
set(CURL_DISABLE_MQTT   ON CACHE BOOL "Disable MQTT" FORCE)
set(CURL_DISABLE_POP3   ON CACHE BOOL "Disable POP3" FORCE)
set(CURL_DISABLE_RTSP   ON CACHE BOOL "Disable RTSP" FORCE)
set(CURL_DISABLE_SMTP   ON CACHE BOOL "Disable SMTP" FORCE)
set(CURL_DISABLE_TELNET ON CACHE BOOL "Disable Telnet" FORCE)
set(CURL_DISABLE_TFTP   ON CACHE BOOL "Disable TFTP" FORCE)
set(CURL_DISABLE_IPFS   ON CACHE BOOL "Disable IPFS" FORCE)
set(CURL_DISABLE_DOH    ON CACHE BOOL "Disable DNS-over-HTTPS" FORCE)

# Disabled optional dependencies and protocol extensions.
set(USE_NGHTTP2           OFF CACHE BOOL   "Disable HTTP/2 support" FORCE)
set(USE_NGTCP2            OFF CACHE BOOL   "Disable ngtcp2 HTTP/3 support" FORCE)
set(USE_QUICHE            OFF CACHE BOOL   "Disable quiche HTTP/3 support" FORCE)
set(USE_HTTPSRR           OFF CACHE BOOL   "Disable HTTPS RR support" FORCE)
set(USE_ECH               OFF CACHE BOOL   "Disable ECH support" FORCE)
set(USE_SSLS_EXPORT       OFF CACHE BOOL   "Disable SSL session export support" FORCE)
set(USE_PROXY_HTTP3       OFF CACHE BOOL   "Disable HTTP/3 proxy support" FORCE)
set(CURL_ZLIB             OFF CACHE STRING "Disable zlib support" FORCE)
set(CURL_BROTLI           OFF CACHE STRING "Disable brotli support" FORCE)
set(CURL_ZSTD             OFF CACHE STRING "Disable zstd support" FORCE)
set(USE_LIBIDN2           OFF CACHE BOOL   "Disable libidn2 support" FORCE)
set(CURL_USE_LIBPSL       OFF CACHE BOOL   "Disable libpsl" FORCE)
set(CURL_USE_LIBSSH2      OFF CACHE BOOL   "Disable libssh2" FORCE)
set(CURL_USE_LIBSSH       OFF CACHE BOOL   "Disable libssh" FORCE)
set(CURL_USE_GSASL        OFF CACHE BOOL   "Disable libgsasl" FORCE)
set(CURL_USE_GSSAPI       OFF CACHE BOOL   "Disable GSSAPI" FORCE)
set(CURL_USE_LIBBACKTRACE OFF CACHE BOOL   "Disable libbacktrace" FORCE)
set(CURL_USE_LIBUV        OFF CACHE BOOL   "Disable libuv" FORCE)
set(ENABLE_UNIX_SOCKETS   OFF CACHE BOOL   "Disable Unix domain sockets support" FORCE)

# Disabled HTTP-side features not needed by the async client use case.
set(CURL_DISABLE_ALTSVC         ON CACHE BOOL "Disable alt-svc support" FORCE)
set(CURL_DISABLE_HSTS           ON CACHE BOOL "Disable HSTS support" FORCE)
set(CURL_DISABLE_SRP            ON CACHE BOOL "Disable TLS-SRP support" FORCE)
set(CURL_DISABLE_PROXY          ON CACHE BOOL "Disable proxy support" FORCE)
set(CURL_DISABLE_COOKIES        ON CACHE BOOL "Disable cookies support" FORCE)
set(CURL_DISABLE_HTTP_AUTH      ON CACHE BOOL "Disable all HTTP authentication methods" FORCE)
set(CURL_DISABLE_BINDLOCAL      ON CACHE BOOL "Disable local binding support" FORCE)
set(CURL_DISABLE_BASIC_AUTH     ON CACHE BOOL "Disable Basic authentication" FORCE)
set(CURL_DISABLE_BEARER_AUTH    ON CACHE BOOL "Disable Bearer authentication" FORCE)
set(CURL_DISABLE_DIGEST_AUTH    ON CACHE BOOL "Disable Digest authentication" FORCE)
set(CURL_DISABLE_KERBEROS_AUTH  ON CACHE BOOL "Disable Kerberos authentication" FORCE)
set(CURL_DISABLE_NEGOTIATE_AUTH ON CACHE BOOL "Disable negotiate authentication" FORCE)
set(CURL_DISABLE_AWS            ON CACHE BOOL "Disable aws-sigv4" FORCE)
set(CURL_DISABLE_MIME           ON CACHE BOOL "Disable MIME support" FORCE)
set(CURL_DISABLE_FORM_API       ON CACHE BOOL "Disable form-api" FORCE)
set(CURL_DISABLE_NETRC          ON CACHE BOOL "Disable netrc parser" FORCE)
set(CURL_DISABLE_PROGRESS_METER ON CACHE BOOL "Disable built-in progress meter" FORCE)
set(CURL_DISABLE_HEADERS_API    ON CACHE BOOL "Disable headers-api support" FORCE)
set(CURL_DISABLE_GETOPTIONS     ON CACHE BOOL "Disable curl_easy_options API" FORCE)
set(CURL_DISABLE_LIBCURL_OPTION ON CACHE BOOL "Disable curl tool --libcurl option" FORCE)

# External dependencies.
set(OPENSSL_ROOT_DIR    "${CURL_THIRD_DIR}/openssl-3.0.20/${CURL_3RD_PLATFORM_DIR}" CACHE PATH "OpenSSL root" FORCE)
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include"                               CACHE PATH "OpenSSL include directory" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libssl.lib" CACHE FILEPATH "OpenSSL SSL library" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libcrypto.lib" CACHE FILEPATH "OpenSSL Crypto library" FORCE)
    curl_copy_runtime_dependency("${OPENSSL_ROOT_DIR}/lib/libssl-3-x64.dll")
    curl_copy_runtime_dependency("${OPENSSL_ROOT_DIR}/lib/libcrypto-3-x64.dll")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libssl.so.3" CACHE FILEPATH "OpenSSL SSL library" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libcrypto.so.3" CACHE FILEPATH "OpenSSL Crypto library" FORCE)
    curl_copy_runtime_dependency("${OPENSSL_SSL_LIBRARY}")
    curl_copy_runtime_dependency("${OPENSSL_CRYPTO_LIBRARY}")
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON CACHE BOOL "Use install RPATH for build-tree binaries" FORCE)
    set(CMAKE_BUILD_RPATH "$ORIGIN" CACHE STRING "Build-tree runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH "$ORIGIN" CACHE STRING "Install runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH_USE_LINK_PATH OFF CACHE BOOL "Do not append link paths to install RPATH" FORCE)
    foreach(CURL_LINKER_FLAG_VAR CMAKE_SHARED_LINKER_FLAGS CMAKE_EXE_LINKER_FLAGS)
        set(CURL_LINKER_FLAGS "${${CURL_LINKER_FLAG_VAR}}")
        set(CURL_RPATH_LINK_FLAG "-Wl,-rpath-link,${OPENSSL_ROOT_DIR}/lib")
        string(FIND "${CURL_LINKER_FLAGS}" "${CURL_RPATH_LINK_FLAG}" CURL_RPATH_LINK_FOUND)
        if(CURL_RPATH_LINK_FOUND EQUAL -1)
            string(APPEND CURL_LINKER_FLAGS " ${CURL_RPATH_LINK_FLAG}")
        endif()
        set(${CURL_LINKER_FLAG_VAR} "${CURL_LINKER_FLAGS}" CACHE STRING "Linux linker flags" FORCE)
    endforeach()
endif()
