set(CURL_PRESET_ROOT "${CMAKE_CURRENT_LIST_DIR}/../curl" CACHE PATH "curl preset root" FORCE)
set(CURL_THIRD_DIR "${CURL_PRESET_ROOT}/../../../3rd-libs" CACHE PATH "curl third-party dependency root" FORCE)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(CURL_PLATFORM_DIR "windows")
    set(CURL_3RD_PLATFORM_DIR "x64-windows")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(CURL_PLATFORM_DIR "linux")
    set(CURL_3RD_PLATFORM_DIR "x64-ubuntu-24.04")
else()
    message(FATAL_ERROR "Unsupported host platform for curl.cmake: ${CMAKE_HOST_SYSTEM_NAME}")
endif()

# Language standards
set(CMAKE_C_STANDARD 11 CACHE STRING "C standard" FORCE)
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C standard" FORCE)
set(CMAKE_C_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C extensions" FORCE)
set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C++ standard" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C++ extensions" FORCE)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    foreach(CURL_FLAG_VAR CMAKE_C_FLAGS CMAKE_CXX_FLAGS)
        set(CURL_FLAGS "${${CURL_FLAG_VAR}}")
        if(NOT CURL_FLAGS MATCHES "(^| )/MP( |$)")
            string(APPEND CURL_FLAGS " /MP")
        endif()
        if(NOT CURL_FLAGS MATCHES "(^| )/utf-8( |$)")
            string(APPEND CURL_FLAGS " /utf-8")
        endif()
        if(NOT CURL_FLAGS MATCHES "(^| )/wd4819( |$)")
            string(APPEND CURL_FLAGS " /wd4819")
        endif()
        set(${CURL_FLAG_VAR} "${CURL_FLAGS}" CACHE STRING "MSVC compiler flags" FORCE)
    endforeach()

    set(CURL_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    if(NOT CURL_CXX_FLAGS MATCHES "(^| )/EHsc( |$)")
        string(APPEND CURL_CXX_FLAGS " /EHsc")
    endif()
    set(CMAKE_CXX_FLAGS "${CURL_CXX_FLAGS}" CACHE STRING "MSVC C++ compiler flags" FORCE)
endif()

# Core build behavior
set(CURL_OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin" CACHE PATH "curl build output directory" FORCE)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CURL_OUTPUT_DIR}" CACHE PATH "Runtime output" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CURL_OUTPUT_DIR}" CACHE PATH "Library output" FORCE)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CURL_OUTPUT_DIR}" CACHE PATH "Archive output" FORCE)
foreach(CURL_OUTPUT_CONFIG Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${CURL_OUTPUT_CONFIG}" CURL_OUTPUT_CONFIG_UPPER)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CURL_OUTPUT_CONFIG_UPPER} "${CURL_OUTPUT_DIR}" CACHE PATH "Runtime output for ${CURL_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CURL_OUTPUT_CONFIG_UPPER} "${CURL_OUTPUT_DIR}" CACHE PATH "Library output for ${CURL_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CURL_OUTPUT_CONFIG_UPPER} "${CURL_OUTPUT_DIR}" CACHE PATH "Archive output for ${CURL_OUTPUT_CONFIG}" FORCE)
endforeach()

function(curl_copy_runtime_dependency CURL_RUNTIME_SOURCE)
    if(ARGC GREATER 1)
        set(CURL_RUNTIME_NAME "${ARGV1}")
    else()
        get_filename_component(CURL_RUNTIME_NAME "${CURL_RUNTIME_SOURCE}" NAME)
    endif()

    if(NOT EXISTS "${CURL_RUNTIME_SOURCE}")
        message(FATAL_ERROR "Missing curl runtime dependency: ${CURL_RUNTIME_SOURCE}")
    endif()

    file(MAKE_DIRECTORY "${CURL_OUTPUT_DIR}")
    file(COPY_FILE "${CURL_RUNTIME_SOURCE}" "${CURL_OUTPUT_DIR}/${CURL_RUNTIME_NAME}" ONLY_IF_DIFFERENT)
endfunction()

# curl build options
set(CURL_WERROR OFF CACHE BOOL "Do not turn compiler warnings into errors" FORCE)
set(PICKY_COMPILER OFF CACHE BOOL "Disable curl maintainer compiler warnings" FORCE)
set(BUILD_SHARED_LIBS ON CACHE BOOL "Build curl shared library" FORCE)
set(BUILD_STATIC_LIBS OFF CACHE BOOL "Do not build curl static library" FORCE)
set(BUILD_CURL_EXE OFF CACHE BOOL "Do not build curl command line tool" FORCE)
set(BUILD_STATIC_CURL OFF CACHE BOOL "Do not build static curl executable" FORCE)
set(CURL_DISABLE_INSTALL ON CACHE BOOL "Do not install curl" FORCE)
set(CURL_BUILD_EVERYTHING OFF CACHE BOOL "Do not build optional curl targets by default" FORCE)
set(CURL_ENABLE_EXPORT_TARGET OFF CACHE BOOL "Do not export curl package targets" FORCE)

set(BUILD_EXAMPLES OFF CACHE BOOL "Do not build curl examples" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "Do not build curl tests" FORCE)
set(CURL_BUILD_TESTING OFF CACHE BOOL "Do not build curl tests" FORCE)
set(BUILD_LIBCURL_DOCS OFF CACHE BOOL "Do not build libcurl docs" FORCE)
set(BUILD_MISC_DOCS OFF CACHE BOOL "Do not build curl misc docs" FORCE)
set(ENABLE_CURL_MANUAL OFF CACHE BOOL "Do not build curl manual" FORCE)
set(CURL_LINT OFF CACHE BOOL "Do not build curl lint targets" FORCE)
set(CURL_LTO OFF CACHE BOOL "Disable curl link time optimization" FORCE)
set(ENABLE_DEBUG OFF CACHE BOOL "Disable curl debug features" FORCE)
set(CURL_CLANG_TIDY OFF CACHE BOOL "Do not run clang-tidy" FORCE)
set(CURL_GCC_ANALYZER OFF CACHE BOOL "Do not run GCC analyzer" FORCE)
set(CURL_CODE_COVERAGE OFF CACHE BOOL "Disable curl code coverage" FORCE)
set(CURL_DROP_UNUSED OFF CACHE BOOL "Do not drop unused code and data" FORCE)

set(HTTP_ONLY ON CACHE BOOL "Build only HTTP/HTTPS protocols" FORCE)
set(ENABLE_IPV6 ON CACHE BOOL "Enable IPv6 support" FORCE)
set(CURL_ENABLE_SSL ON CACHE BOOL "Enable TLS support" FORCE)
set(CURL_USE_OPENSSL ON CACHE BOOL "Use OpenSSL TLS backend" FORCE)
set(CURL_DEFAULT_SSL_BACKEND "openssl" CACHE STRING "Default curl TLS backend" FORCE)
set(CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG OFF CACHE BOOL "Allow OpenSSL to load its configuration" FORCE)
set(OPENSSL_USE_STATIC_LIBS OFF CACHE BOOL "Link OpenSSL shared libraries" FORCE)
set(CURL_USE_SCHANNEL OFF CACHE BOOL "Disable Schannel TLS backend" FORCE)
set(CURL_USE_MBEDTLS OFF CACHE BOOL "Disable mbedTLS TLS backend" FORCE)
set(CURL_USE_WOLFSSL OFF CACHE BOOL "Disable wolfSSL TLS backend" FORCE)
set(CURL_USE_GNUTLS OFF CACHE BOOL "Disable GnuTLS TLS backend" FORCE)
set(CURL_USE_RUSTLS OFF CACHE BOOL "Disable Rustls TLS backend" FORCE)
set(USE_HTTPSRR OFF CACHE BOOL "Disable HTTPS RR support" FORCE)
set(USE_ECH OFF CACHE BOOL "Disable ECH support" FORCE)
set(USE_SSLS_EXPORT OFF CACHE BOOL "Disable SSL session export support" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(CURL_USE_CMAKECONFIG ON CACHE BOOL "Use CMake config files for dependency detection" FORCE)
    set(CURL_USE_PKGCONFIG OFF CACHE BOOL "Disable pkg-config dependency detection" FORCE)
else()
    set(CURL_USE_CMAKECONFIG OFF CACHE BOOL "Disable CMake config dependency detection" FORCE)
    set(CURL_USE_PKGCONFIG ON CACHE BOOL "Use pkg-config dependency detection" FORCE)
endif()

set(ENABLE_ARES OFF CACHE BOOL "Disable c-ares dependency" FORCE)
set(ENABLE_THREADED_RESOLVER ON CACHE BOOL "Use threaded DNS resolver" FORCE)
set(USE_NGHTTP2 OFF CACHE BOOL "Disable HTTP/2 dependency" FORCE)
set(USE_NGTCP2 OFF CACHE BOOL "Disable HTTP/3 ngtcp2 dependency" FORCE)
set(USE_QUICHE OFF CACHE BOOL "Disable HTTP/3 quiche dependency" FORCE)
set(USE_LIBIDN2 OFF CACHE BOOL "Disable libidn2 dependency" FORCE)
set(CURL_USE_LIBPSL OFF CACHE BOOL "Disable libpsl dependency" FORCE)
set(CURL_USE_LIBSSH2 OFF CACHE BOOL "Disable libssh2 dependency" FORCE)
set(CURL_USE_LIBSSH OFF CACHE BOOL "Disable libssh dependency" FORCE)
set(CURL_USE_GSASL OFF CACHE BOOL "Disable libgsasl dependency" FORCE)
set(CURL_USE_GSSAPI OFF CACHE BOOL "Disable GSSAPI dependency" FORCE)
set(CURL_USE_LIBBACKTRACE OFF CACHE BOOL "Disable libbacktrace dependency" FORCE)
set(CURL_USE_LIBUV OFF CACHE BOOL "Disable libuv dependency" FORCE)
set(CURL_ZLIB OFF CACHE STRING "Disable zlib dependency" FORCE)
set(CURL_BROTLI OFF CACHE STRING "Disable brotli dependency" FORCE)
set(CURL_ZSTD OFF CACHE STRING "Disable zstd dependency" FORCE)

set(CURL_DISABLE_ALTSVC ON CACHE BOOL "Disable alt-svc support" FORCE)
set(CURL_DISABLE_AWS ON CACHE BOOL "Disable aws-sigv4 support" FORCE)
set(CURL_DISABLE_BASIC_AUTH OFF CACHE BOOL "Enable Basic authentication" FORCE)
set(CURL_DISABLE_BEARER_AUTH OFF CACHE BOOL "Enable Bearer authentication" FORCE)
set(CURL_DISABLE_BINDLOCAL ON CACHE BOOL "Disable local binding support" FORCE)
set(CURL_DISABLE_COOKIES ON CACHE BOOL "Disable cookies support" FORCE)
set(CURL_DISABLE_DIGEST_AUTH OFF CACHE BOOL "Enable Digest authentication" FORCE)
set(CURL_DISABLE_DICT ON CACHE BOOL "Disable DICT protocol" FORCE)
set(CURL_DISABLE_DOH ON CACHE BOOL "Disable DNS-over-HTTPS support" FORCE)
set(CURL_DISABLE_FILE ON CACHE BOOL "Disable FILE protocol" FORCE)
set(CURL_DISABLE_FTP ON CACHE BOOL "Disable FTP protocol" FORCE)
set(CURL_DISABLE_FORM_API ON CACHE BOOL "Disable form API support" FORCE)
set(CURL_DISABLE_GETOPTIONS OFF CACHE BOOL "Enable curl_easy_options API" FORCE)
set(CURL_DISABLE_GOPHER ON CACHE BOOL "Disable Gopher protocol" FORCE)
set(CURL_DISABLE_HEADERS_API OFF CACHE BOOL "Enable headers API support" FORCE)
set(CURL_DISABLE_HSTS ON CACHE BOOL "Disable HSTS support" FORCE)
set(CURL_DISABLE_HTTP OFF CACHE BOOL "Enable HTTP protocol" FORCE)
set(CURL_DISABLE_HTTP_AUTH OFF CACHE BOOL "Enable HTTP authentication support" FORCE)
set(CURL_DISABLE_IMAP ON CACHE BOOL "Disable IMAP protocol" FORCE)
set(CURL_DISABLE_IPFS ON CACHE BOOL "Disable IPFS protocol" FORCE)
set(CURL_DISABLE_KERBEROS_AUTH ON CACHE BOOL "Disable Kerberos authentication" FORCE)
set(CURL_DISABLE_LDAP ON CACHE BOOL "Disable LDAP protocol" FORCE)
set(CURL_DISABLE_LDAPS ON CACHE BOOL "Disable LDAPS protocol" FORCE)
set(CURL_DISABLE_LIBCURL_OPTION ON CACHE BOOL "Disable --libcurl option from curl tool" FORCE)
set(CURL_DISABLE_MIME ON CACHE BOOL "Disable MIME support" FORCE)
set(CURL_DISABLE_MQTT ON CACHE BOOL "Disable MQTT protocol" FORCE)
set(CURL_DISABLE_NEGOTIATE_AUTH ON CACHE BOOL "Disable negotiate auth support" FORCE)
set(CURL_DISABLE_NETRC ON CACHE BOOL "Disable netrc parser" FORCE)
set(CURL_DISABLE_PARSEDATE OFF CACHE BOOL "Enable date parsing" FORCE)
set(CURL_DISABLE_POP3 ON CACHE BOOL "Disable POP3 protocol" FORCE)
set(CURL_DISABLE_PROGRESS_METER ON CACHE BOOL "Disable built-in progress meter" FORCE)
set(CURL_DISABLE_PROXY ON CACHE BOOL "Disable proxy support" FORCE)
set(CURL_DISABLE_RTSP ON CACHE BOOL "Disable RTSP protocol" FORCE)
set(CURL_DISABLE_SHA512_256 OFF CACHE BOOL "Enable SHA-512/256 hash algorithm" FORCE)
set(CURL_DISABLE_SHUFFLE_DNS ON CACHE BOOL "Disable shuffle DNS feature" FORCE)
set(CURL_DISABLE_SMTP ON CACHE BOOL "Disable SMTP protocol" FORCE)
set(CURL_DISABLE_SOCKETPAIR OFF CACHE BOOL "Enable socketpair for curl_multi_poll()" FORCE)
set(CURL_DISABLE_SRP ON CACHE BOOL "Disable TLS-SRP support" FORCE)
set(CURL_DISABLE_TELNET ON CACHE BOOL "Disable Telnet protocol" FORCE)
set(CURL_DISABLE_TFTP ON CACHE BOOL "Disable TFTP protocol" FORCE)
set(CURL_DISABLE_TYPECHECK OFF CACHE BOOL "Enable curl_easy_setopt type checking" FORCE)
set(CURL_DISABLE_VERBOSE_STRINGS OFF CACHE BOOL "Enable verbose strings" FORCE)
set(CURL_DISABLE_WEBSOCKETS ON CACHE BOOL "Disable WebSocket support" FORCE)
set(CURL_DEBUG_GLOBAL_MEM OFF CACHE BOOL "Disable curl global memory debugging" FORCE)
set(CURL_ENABLE_NTLM OFF CACHE BOOL "Disable NTLM support" FORCE)
set(CURL_ENABLE_SMB OFF CACHE BOOL "Disable SMB support" FORCE)
set(ENABLE_UNIX_SOCKETS OFF CACHE BOOL "Disable Unix domain sockets support" FORCE)
set(USE_APPLE_IDN OFF CACHE BOOL "Disable Apple IDN support" FORCE)
set(USE_APPLE_SECTRUST OFF CACHE BOOL "Disable Apple SecTrust support" FORCE)

set(LIBCURL_OUTPUT_NAME "libcurl" CACHE STRING "Basename of the curl library" FORCE)
set(CURL_LIBCURL_VERSIONED_SYMBOLS OFF CACHE BOOL "Disable libcurl versioned symbols" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(ENABLE_UNICODE OFF CACHE BOOL "Disable Windows Unicode API mode" FORCE)
    set(CURL_TARGET_WINDOWS_VERSION "0x0A00" CACHE STRING "Minimum target Windows version" FORCE)
    set(CURL_CA_NATIVE OFF CACHE BOOL "Use Windows native CA store when available" FORCE)
    set(CURL_WINDOWS_SSPI OFF CACHE BOOL "Disable Windows SSPI support" FORCE)
    set(CURL_STATIC_CRT OFF CACHE BOOL "Use MSVC dynamic runtime" FORCE)
    set(USE_WIN32_IDN OFF CACHE BOOL "Disable WinIDN support" FORCE)
    set(USE_WIN32_LDAP OFF CACHE BOOL "Disable Windows LDAP implementation" FORCE)
    set(CURL_DISABLE_CA_SEARCH OFF CACHE BOOL "Allow curl's default Windows CA bundle search behavior" FORCE)
    set(CURL_CA_SEARCH_SAFE OFF CACHE BOOL "Disable safe CA bundle search" FORCE)
    set(CURL_LIBCURL_SOVERSION OFF CACHE BOOL "Disable libcurl SOVERSION" FORCE)
else()
    set(CURL_CA_NATIVE OFF CACHE BOOL "Use system CA bundle/path detection" FORCE)
    set(CURL_LIBCURL_SOVERSION ON CACHE BOOL "Enable libcurl SOVERSION" FORCE)
endif()
set(CURL_CA_BUNDLE "auto" CACHE STRING "Auto-detect CA bundle when supported" FORCE)
set(CURL_CA_FALLBACK OFF CACHE BOOL "Do not use OpenSSL built-in CA fallback" FORCE)
set(CURL_CA_PATH "auto" CACHE STRING "Auto-detect CA path when supported" FORCE)
set(CURL_CA_EMBED "" CACHE STRING "Do not embed a CA bundle in the curl tool" FORCE)

# External dependencies
set(OPENSSL_ROOT_DIR "${CURL_THIRD_DIR}/openssl-3.0.20/${CURL_3RD_PLATFORM_DIR}" CACHE PATH "OpenSSL root" FORCE)
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include" CACHE PATH "OpenSSL include directory" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON CACHE BOOL "Use install RPATH for build-tree binaries" FORCE)
    set(CMAKE_BUILD_RPATH "$ORIGIN" CACHE STRING "Build-tree runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH "$ORIGIN" CACHE STRING "Install runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH_USE_LINK_PATH OFF CACHE BOOL "Do not append link paths to install RPATH" FORCE)
    foreach(CURL_LINKER_FLAG_VAR CMAKE_SHARED_LINKER_FLAGS CMAKE_EXE_LINKER_FLAGS)
        set(CURL_LINKER_FLAGS "${${CURL_LINKER_FLAG_VAR}}")
        set(CURL_RPATH_LINK_FLAG "-Wl,-rpath-link,${OPENSSL_ROOT_DIR}/lib")
        string(FIND "${CURL_LINKER_FLAGS}" "${CURL_RPATH_LINK_FLAG}" CURL_RPATH_LINK_FOUND)
        if(CURL_RPATH_LINK_FOUND EQUAL -1)
            string(APPEND CURL_LINKER_FLAGS " ${CURL_RPATH_LINK_FLAG}")
        endif()
        set(${CURL_LINKER_FLAG_VAR} "${CURL_LINKER_FLAGS}" CACHE STRING "Linux linker flags" FORCE)
    endforeach()
endif()
