# 项目名字
SET(CURRENT_TARGET_NAME distorm)

# 头文件目录
SET(CURRENT_PRIVATE_INCLUDE_DIRS
    # ...
)

SET(CURRENT_PUBLIC_INCLUDE_DIRS
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/include
)

# 宏定义、编译选项、链接库
IF(WIN32)
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        -DDISTORM_DYNAMIC
        -DSUPPORT_64BIT_OFFSET
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        # ...
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        /wd4828
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        # ...
    )
ELSE()
    # 宏定义
    SET(CURRENT_PRIVATE_COMPILE_DEFINITIONS
        -DDISTORM_DYNAMIC
        -DSUPPORT_64BIT_OFFSET
    )

    SET(CURRENT_PUBLIC_COMPILE_DEFINITIONS
        # ...
    )

    # 编译选项
    SET(CURRENT_COMPILE_OPTIONS
        -Wno-unused-function
        -Wno-overlength-strings
        -Wno-implicit-fallthrough
    )

    # 链接库
    SET(CURRENT_LINK_LIBS
        # ...
    )
ENDIF()

# distorm头文件
FILE(GLOB_RECURSE DISTORM_INCLUDE_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/include/*.h
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/include/*.inl
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/include/*.hpp
)

# distorm源文件
FILE(GLOB_RECURSE DISTORM_SRC_LIST
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/src/*.c
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/src/*.cc
    ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm/src/*.cpp
)

# 生成动态库
ADD_LIBRARY(${CURRENT_TARGET_NAME} SHARED ${DISTORM_INCLUDE_LIST} ${DISTORM_SRC_LIST})
PROJECT_TARGET_APPLY_COMMON_OPTIONS(${CURRENT_TARGET_NAME})
TARGET_INCLUDE_DIRECTORIES(${CURRENT_TARGET_NAME} PRIVATE ${CURRENT_PRIVATE_INCLUDE_DIRS})
TARGET_INCLUDE_DIRECTORIES(${CURRENT_TARGET_NAME} PUBLIC  ${CURRENT_PUBLIC_INCLUDE_DIRS})
TARGET_COMPILE_DEFINITIONS(${CURRENT_TARGET_NAME} PRIVATE ${CURRENT_PRIVATE_COMPILE_DEFINITIONS})
TARGET_COMPILE_DEFINITIONS(${CURRENT_TARGET_NAME} PUBLIC  ${CURRENT_PUBLIC_COMPILE_DEFINITIONS})
TARGET_COMPILE_OPTIONS(${CURRENT_TARGET_NAME}     PRIVATE ${CURRENT_COMPILE_OPTIONS})
TARGET_LINK_LIBRARIES(${CURRENT_TARGET_NAME}      PUBLIC  ${CURRENT_LINK_LIBS})

# 拷贝构建产物至工作目录
PROJECT_TARGET_COPY_RUNTIME_TO_WORKDIR(${CURRENT_TARGET_NAME})

# 其它设置
IF(WIN32)
    # MSVC运行库设置
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")

    # VS工程设置
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY FOLDER "3rd/funchook")
    SET_PROPERTY(TARGET ${CURRENT_TARGET_NAME} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_DEBUGGER_WORKING_DIRECTORY}")

    SOURCE_GROUP(TREE ${CMAKE_PROJECT_ROOT_DIR}/3rd/distorm PREFIX "distorm"
        FILES ${DISTORM_INCLUDE_LIST} ${DISTORM_SRC_LIST})
ENDIF()
