IF(WIN32)
    SET(LIBHV_BUILD_DIR "${CMAKE_PROJECT_ROOT_DIR}/3rd/libhv/.build/windows/x64-${CMAKE_BUILD_TYPE}/bin" CACHE PATH "libhv build directory" FORCE)
ELSE()
    SET(LIBHV_BUILD_DIR "${CMAKE_PROJECT_ROOT_DIR}/3rd/libhv/.build/linux/x64-${CMAKE_BUILD_TYPE}/bin"   CACHE PATH "libhv build directory" FORCE)
ENDIF()

IF(WIN32)
    SET(LIBHV_IMPORTED_LOCATION "${LIBHV_BUILD_DIR}/hv.dll" CACHE FILEPATH "libhv runtime library" FORCE)
    SET(LIBHV_IMPORTED_IMPLIB   "${LIBHV_BUILD_DIR}/hv.lib" CACHE FILEPATH "libhv import library" FORCE)
ELSE()
    SET(LIBHV_IMPORTED_LOCATION "${LIBHV_BUILD_DIR}/libhv.so" CACHE FILEPATH "libhv runtime library" FORCE)
ENDIF()

SET(LIBHV_INCLUDE_DIR "${LIBHV_BUILD_DIR}/../include" CACHE PATH "libhv include directory" FORCE)
IF(NOT EXISTS "${LIBHV_INCLUDE_DIR}/hv/hv.h")
    MESSAGE(FATAL_ERROR "libhv header not found: ${LIBHV_INCLUDE_DIR}/hv/hv.h")
ENDIF()

IF(WIN32)
    IF(NOT EXISTS "${LIBHV_IMPORTED_LOCATION}")
        MESSAGE(FATAL_ERROR "libhv runtime library not found: ${LIBHV_IMPORTED_LOCATION}")
    ENDIF()

    IF(NOT EXISTS "${LIBHV_IMPORTED_IMPLIB}")
        MESSAGE(FATAL_ERROR "libhv import library not found: ${LIBHV_IMPORTED_IMPLIB}")
    ENDIF()
ELSE()
    IF(NOT EXISTS "${LIBHV_IMPORTED_LOCATION}")
        MESSAGE(FATAL_ERROR "libhv runtime library not found: ${LIBHV_IMPORTED_LOCATION}")
    ENDIF()
ENDIF()

ADD_LIBRARY(hv SHARED IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(hv PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${LIBHV_INCLUDE_DIR}"
    IMPORTED_LOCATION             "${LIBHV_IMPORTED_LOCATION}"
)

IF(WIN32)
    SET_TARGET_PROPERTIES(hv PROPERTIES
        IMPORTED_IMPLIB "${LIBHV_IMPORTED_IMPLIB}"
    )
ELSE()
    SET_TARGET_PROPERTIES(hv PROPERTIES
        IMPORTED_SONAME "libhv.so"
    )
ENDIF()

IF(NOT TARGET hv::libhv)
    ADD_LIBRARY(hv::libhv ALIAS hv)
ENDIF()

FUNCTION(PROJECT_GET_LIBHV_RUNTIME_COPY_COMMANDS OUTPUT_VARIABLE)
    SET(LIBHV_RUNTIME_COPY_COMMANDS
        COMMAND ${CMAKE_COMMAND} -E make_directory
            "${PROJECT_DEBUGGER_WORKING_DIRECTORY}"
    )

    LIST(APPEND LIBHV_RUNTIME_COPY_COMMANDS
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${LIBHV_IMPORTED_LOCATION}"
            "${PROJECT_DEBUGGER_WORKING_DIRECTORY}"
    )

    SET(${OUTPUT_VARIABLE} ${LIBHV_RUNTIME_COPY_COMMANDS} PARENT_SCOPE)
ENDFUNCTION()

PROJECT_GET_LIBHV_RUNTIME_COPY_COMMANDS(LIBHV_RUNTIME_COPY_COMMANDS)
ADD_CUSTOM_TARGET(libhv_runtime_copy
    ${LIBHV_RUNTIME_COPY_COMMANDS}
    VERBATIM
)
ADD_DEPENDENCIES(hv libhv_runtime_copy)

IF(WIN32)
    SET_PROPERTY(TARGET libhv_runtime_copy PROPERTY FOLDER "cmake")
ENDIF()

IF(WIN32 AND CMAKE_GENERATOR MATCHES "Visual Studio")
    SET(LIBHV_VSPROJ_BUILD_DIR "${CMAKE_PROJECT_ROOT_DIR}/3rd/libhv/.build/windows/x64-${CMAKE_BUILD_TYPE}")

    FUNCTION(ADD_LIBHV_EXTERNAL_MSPROJECT TARGET_NAME PROJECT_PATH)
        SET(LIBHV_VSPROJ "${LIBHV_VSPROJ_BUILD_DIR}/${PROJECT_PATH}")

        IF(EXISTS "${LIBHV_VSPROJ}")
            INCLUDE_EXTERNAL_MSPROJECT(
                ${TARGET_NAME}
                "${LIBHV_VSPROJ}"
                PLATFORM x64
            )

            SET_PROPERTY(TARGET ${TARGET_NAME} PROPERTY FOLDER "3rd/libhv")
        ELSE()
            MESSAGE(WARNING
                "libhv vcxproj not found: ${LIBHV_VSPROJ}. "
                "Run 3rd/3rd-cmake/libhv.build.bat ${CMAKE_BUILD_TYPE} before generating the main Visual Studio solution."
            )
        ENDIF()
    ENDFUNCTION()

    ADD_LIBHV_EXTERNAL_MSPROJECT(libhv "hv.vcxproj")
ENDIF()
