// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMsgDefine.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TestMsgDefine_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TestMsgDefine_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TestMsgDefine_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TestMsgDefine_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMsgDefine_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace TestMsg {

enum TestCommonType : int {
  CT_FLOAT = 0,
  CT_DOUBLE = 1,
  CT_BYTES = 2,
  CT_INT32 = 3,
  CT_SINT32 = 4,
  CT_UINT32 = 5,
  CT_INT64 = 6,
  CT_SINT64 = 7,
  CT_UINT64 = 8,
  TestCommonType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TestCommonType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TestCommonType_IsValid(int value);
constexpr TestCommonType TestCommonType_MIN = CT_FLOAT;
constexpr TestCommonType TestCommonType_MAX = CT_UINT64;
constexpr int TestCommonType_ARRAYSIZE = TestCommonType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TestCommonType_descriptor();
template<typename T>
inline const std::string& TestCommonType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TestCommonType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TestCommonType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TestCommonType_descriptor(), enum_t_value);
}
inline bool TestCommonType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TestCommonType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TestCommonType>(
    TestCommonType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace TestMsg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::TestMsg::TestCommonType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TestMsg::TestCommonType>() {
  return ::TestMsg::TestCommonType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TestMsgDefine_2eproto
