// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMsgDefine.proto

#include "TestMsgDefine.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace TestMsg {
}  // namespace TestMsg
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_TestMsgDefine_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_TestMsgDefine_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TestMsgDefine_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_TestMsgDefine_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_TestMsgDefine_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023TestMsgDefine.proto\022\007TestMsg*\217\001\n\nCommo"
  "nType\022\014\n\010CT_FLOAT\020\000\022\r\n\tCT_DOUBLE\020\001\022\014\n\010CT"
  "_BYTES\020\002\022\014\n\010CT_INT32\020\003\022\r\n\tCT_SINT32\020\004\022\r\n"
  "\tCT_UINT32\020\005\022\014\n\010CT_INT64\020\006\022\r\n\tCT_SINT64\020"
  "\007\022\r\n\tCT_UINT64\020\010b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TestMsgDefine_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMsgDefine_2eproto = {
  false, false, 184, descriptor_table_protodef_TestMsgDefine_2eproto, "TestMsgDefine.proto", 
  &descriptor_table_TestMsgDefine_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_TestMsgDefine_2eproto::offsets,
  file_level_metadata_TestMsgDefine_2eproto, file_level_enum_descriptors_TestMsgDefine_2eproto, file_level_service_descriptors_TestMsgDefine_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_TestMsgDefine_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_TestMsgDefine_2eproto);
  return descriptor_table_TestMsgDefine_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TestMsgDefine_2eproto(&descriptor_table_TestMsgDefine_2eproto);
namespace TestMsg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommonType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_TestMsgDefine_2eproto);
  return file_level_enum_descriptors_TestMsgDefine_2eproto[0];
}
bool CommonType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace TestMsg
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
