// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMsgStruct.proto

#include "TestMsgStruct.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace PBMsg {
constexpr TestCommonInfo::TestCommonInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : test_string_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , test_bool_(false)
  , test_float_(0)
  , test_double_(0)
  , test_int32_(0)
  , test_sint32_(0)
  , test_int64_(int64_t{0})
  , test_sint64_(int64_t{0})
  , test_uint64_(uint64_t{0u})
  , test_uint32_(0u){}
struct TestCommonInfoDefaultTypeInternal {
  constexpr TestCommonInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestCommonInfoDefaultTypeInternal() {}
  union {
    TestCommonInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestCommonInfoDefaultTypeInternal _TestCommonInfo_default_instance_;
constexpr TestCommonInfoList::TestCommonInfoList(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : common_info_list_()
  , common_type_list_()
  , _common_type_list_cached_byte_size_(0){}
struct TestCommonInfoListDefaultTypeInternal {
  constexpr TestCommonInfoListDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestCommonInfoListDefaultTypeInternal() {}
  union {
    TestCommonInfoList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestCommonInfoListDefaultTypeInternal _TestCommonInfoList_default_instance_;
}  // namespace PBMsg
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TestMsgStruct_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TestMsgStruct_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TestMsgStruct_2eproto = nullptr;

const uint32_t TableStruct_TestMsgStruct_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_bool_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_float_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_double_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_string_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_int32_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_sint32_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_uint32_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_int64_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_sint64_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfo, test_uint64_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfoList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfoList, common_info_list_),
  PROTOBUF_FIELD_OFFSET(::PBMsg::TestCommonInfoList, common_type_list_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PBMsg::TestCommonInfo)},
  { 16, -1, -1, sizeof(::PBMsg::TestCommonInfoList)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PBMsg::_TestCommonInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PBMsg::_TestCommonInfoList_default_instance_),
};

const char descriptor_table_protodef_TestMsgStruct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023TestMsgStruct.proto\022\005PBMsg\032\023TestMsgDef"
  "ine.proto\"\335\001\n\016TestCommonInfo\022\021\n\ttest_boo"
  "l\030\001 \001(\010\022\022\n\ntest_float\030\002 \001(\002\022\023\n\013test_doub"
  "le\030\003 \001(\001\022\023\n\013test_string\030\004 \001(\014\022\022\n\ntest_in"
  "t32\030\005 \001(\005\022\023\n\013test_sint32\030\006 \001(\021\022\023\n\013test_u"
  "int32\030\007 \001(\r\022\022\n\ntest_int64\030\010 \001(\003\022\023\n\013test_"
  "sint64\030\t \001(\022\022\023\n\013test_uint64\030\n \001(\004\"v\n\022Tes"
  "tCommonInfoList\022/\n\020common_info_list\030\001 \003("
  "\0132\025.PBMsg.TestCommonInfo\022/\n\020common_type_"
  "list\030\002 \003(\0162\025.PBMsg.TestCommonTypeb\006proto"
  "3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_TestMsgStruct_2eproto_deps[1] = {
  &::descriptor_table_TestMsgDefine_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TestMsgStruct_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMsgStruct_2eproto = {
  false, false, 401, descriptor_table_protodef_TestMsgStruct_2eproto, "TestMsgStruct.proto", 
  &descriptor_table_TestMsgStruct_2eproto_once, descriptor_table_TestMsgStruct_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_TestMsgStruct_2eproto::offsets,
  file_level_metadata_TestMsgStruct_2eproto, file_level_enum_descriptors_TestMsgStruct_2eproto, file_level_service_descriptors_TestMsgStruct_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TestMsgStruct_2eproto_getter() {
  return &descriptor_table_TestMsgStruct_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TestMsgStruct_2eproto(&descriptor_table_TestMsgStruct_2eproto);
namespace PBMsg {

// ===================================================================

class TestCommonInfo::_Internal {
 public:
};

TestCommonInfo::TestCommonInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:PBMsg.TestCommonInfo)
}
TestCommonInfo::TestCommonInfo(const TestCommonInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  test_string_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    test_string_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_test_string().empty()) {
    test_string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_test_string(), 
      GetArenaForAllocation());
  }
  ::memcpy(&test_bool_, &from.test_bool_,
    static_cast<size_t>(reinterpret_cast<char*>(&test_uint32_) -
    reinterpret_cast<char*>(&test_bool_)) + sizeof(test_uint32_));
  // @@protoc_insertion_point(copy_constructor:PBMsg.TestCommonInfo)
}

inline void TestCommonInfo::SharedCtor() {
test_string_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  test_string_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&test_bool_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&test_uint32_) -
    reinterpret_cast<char*>(&test_bool_)) + sizeof(test_uint32_));
}

TestCommonInfo::~TestCommonInfo() {
  // @@protoc_insertion_point(destructor:PBMsg.TestCommonInfo)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestCommonInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  test_string_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TestCommonInfo::ArenaDtor(void* object) {
  TestCommonInfo* _this = reinterpret_cast< TestCommonInfo* >(object);
  (void)_this;
}
void TestCommonInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestCommonInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestCommonInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:PBMsg.TestCommonInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  test_string_.ClearToEmpty();
  ::memset(&test_bool_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&test_uint32_) -
      reinterpret_cast<char*>(&test_bool_)) + sizeof(test_uint32_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestCommonInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool test_bool = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          test_bool_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float test_float = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          test_float_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // double test_double = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          test_double_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bytes test_string = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_test_string();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 test_int32 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          test_int32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 test_sint32 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          test_sint32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 test_uint32 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          test_uint32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 test_int64 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          test_int64_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint64 test_sint64 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          test_sint64_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 test_uint64 = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          test_uint64_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestCommonInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBMsg.TestCommonInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool test_bool = 1;
  if (this->_internal_test_bool() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_test_bool(), target);
  }

  // float test_float = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_test_float = this->_internal_test_float();
  uint32_t raw_test_float;
  memcpy(&raw_test_float, &tmp_test_float, sizeof(tmp_test_float));
  if (raw_test_float != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_test_float(), target);
  }

  // double test_double = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_test_double = this->_internal_test_double();
  uint64_t raw_test_double;
  memcpy(&raw_test_double, &tmp_test_double, sizeof(tmp_test_double));
  if (raw_test_double != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_test_double(), target);
  }

  // bytes test_string = 4;
  if (!this->_internal_test_string().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_test_string(), target);
  }

  // int32 test_int32 = 5;
  if (this->_internal_test_int32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_test_int32(), target);
  }

  // sint32 test_sint32 = 6;
  if (this->_internal_test_sint32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt32ToArray(6, this->_internal_test_sint32(), target);
  }

  // uint32 test_uint32 = 7;
  if (this->_internal_test_uint32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_test_uint32(), target);
  }

  // int64 test_int64 = 8;
  if (this->_internal_test_int64() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(8, this->_internal_test_int64(), target);
  }

  // sint64 test_sint64 = 9;
  if (this->_internal_test_sint64() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt64ToArray(9, this->_internal_test_sint64(), target);
  }

  // uint64 test_uint64 = 10;
  if (this->_internal_test_uint64() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(10, this->_internal_test_uint64(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBMsg.TestCommonInfo)
  return target;
}

size_t TestCommonInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBMsg.TestCommonInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes test_string = 4;
  if (!this->_internal_test_string().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_test_string());
  }

  // bool test_bool = 1;
  if (this->_internal_test_bool() != 0) {
    total_size += 1 + 1;
  }

  // float test_float = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_test_float = this->_internal_test_float();
  uint32_t raw_test_float;
  memcpy(&raw_test_float, &tmp_test_float, sizeof(tmp_test_float));
  if (raw_test_float != 0) {
    total_size += 1 + 4;
  }

  // double test_double = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_test_double = this->_internal_test_double();
  uint64_t raw_test_double;
  memcpy(&raw_test_double, &tmp_test_double, sizeof(tmp_test_double));
  if (raw_test_double != 0) {
    total_size += 1 + 8;
  }

  // int32 test_int32 = 5;
  if (this->_internal_test_int32() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_test_int32());
  }

  // sint32 test_sint32 = 6;
  if (this->_internal_test_sint32() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt32SizePlusOne(this->_internal_test_sint32());
  }

  // int64 test_int64 = 8;
  if (this->_internal_test_int64() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_test_int64());
  }

  // sint64 test_sint64 = 9;
  if (this->_internal_test_sint64() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt64SizePlusOne(this->_internal_test_sint64());
  }

  // uint64 test_uint64 = 10;
  if (this->_internal_test_uint64() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_test_uint64());
  }

  // uint32 test_uint32 = 7;
  if (this->_internal_test_uint32() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_test_uint32());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestCommonInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestCommonInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestCommonInfo::GetClassData() const { return &_class_data_; }

void TestCommonInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestCommonInfo *>(to)->MergeFrom(
      static_cast<const TestCommonInfo &>(from));
}


void TestCommonInfo::MergeFrom(const TestCommonInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PBMsg.TestCommonInfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_test_string().empty()) {
    _internal_set_test_string(from._internal_test_string());
  }
  if (from._internal_test_bool() != 0) {
    _internal_set_test_bool(from._internal_test_bool());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_test_float = from._internal_test_float();
  uint32_t raw_test_float;
  memcpy(&raw_test_float, &tmp_test_float, sizeof(tmp_test_float));
  if (raw_test_float != 0) {
    _internal_set_test_float(from._internal_test_float());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_test_double = from._internal_test_double();
  uint64_t raw_test_double;
  memcpy(&raw_test_double, &tmp_test_double, sizeof(tmp_test_double));
  if (raw_test_double != 0) {
    _internal_set_test_double(from._internal_test_double());
  }
  if (from._internal_test_int32() != 0) {
    _internal_set_test_int32(from._internal_test_int32());
  }
  if (from._internal_test_sint32() != 0) {
    _internal_set_test_sint32(from._internal_test_sint32());
  }
  if (from._internal_test_int64() != 0) {
    _internal_set_test_int64(from._internal_test_int64());
  }
  if (from._internal_test_sint64() != 0) {
    _internal_set_test_sint64(from._internal_test_sint64());
  }
  if (from._internal_test_uint64() != 0) {
    _internal_set_test_uint64(from._internal_test_uint64());
  }
  if (from._internal_test_uint32() != 0) {
    _internal_set_test_uint32(from._internal_test_uint32());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestCommonInfo::CopyFrom(const TestCommonInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBMsg.TestCommonInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestCommonInfo::IsInitialized() const {
  return true;
}

void TestCommonInfo::InternalSwap(TestCommonInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &test_string_, lhs_arena,
      &other->test_string_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestCommonInfo, test_uint32_)
      + sizeof(TestCommonInfo::test_uint32_)
      - PROTOBUF_FIELD_OFFSET(TestCommonInfo, test_bool_)>(
          reinterpret_cast<char*>(&test_bool_),
          reinterpret_cast<char*>(&other->test_bool_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TestCommonInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMsgStruct_2eproto_getter, &descriptor_table_TestMsgStruct_2eproto_once,
      file_level_metadata_TestMsgStruct_2eproto[0]);
}

// ===================================================================

class TestCommonInfoList::_Internal {
 public:
};

TestCommonInfoList::TestCommonInfoList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  common_info_list_(arena),
  common_type_list_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:PBMsg.TestCommonInfoList)
}
TestCommonInfoList::TestCommonInfoList(const TestCommonInfoList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      common_info_list_(from.common_info_list_),
      common_type_list_(from.common_type_list_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PBMsg.TestCommonInfoList)
}

inline void TestCommonInfoList::SharedCtor() {
}

TestCommonInfoList::~TestCommonInfoList() {
  // @@protoc_insertion_point(destructor:PBMsg.TestCommonInfoList)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestCommonInfoList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TestCommonInfoList::ArenaDtor(void* object) {
  TestCommonInfoList* _this = reinterpret_cast< TestCommonInfoList* >(object);
  (void)_this;
}
void TestCommonInfoList::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestCommonInfoList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestCommonInfoList::Clear() {
// @@protoc_insertion_point(message_clear_start:PBMsg.TestCommonInfoList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  common_info_list_.Clear();
  common_type_list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestCommonInfoList::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .PBMsg.TestCommonInfo common_info_list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_common_info_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .PBMsg.TestCommonType common_type_list = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_common_type_list(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_common_type_list(static_cast<::PBMsg::TestCommonType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestCommonInfoList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBMsg.TestCommonInfoList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PBMsg.TestCommonInfo common_info_list = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_common_info_list_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_common_info_list(i), target, stream);
  }

  // repeated .PBMsg.TestCommonType common_type_list = 2;
  {
    int byte_size = _common_type_list_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          2, common_type_list_, byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBMsg.TestCommonInfoList)
  return target;
}

size_t TestCommonInfoList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBMsg.TestCommonInfoList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PBMsg.TestCommonInfo common_info_list = 1;
  total_size += 1UL * this->_internal_common_info_list_size();
  for (const auto& msg : this->common_info_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .PBMsg.TestCommonType common_type_list = 2;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_common_type_list_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_common_type_list(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<int32_t>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _common_type_list_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestCommonInfoList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestCommonInfoList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestCommonInfoList::GetClassData() const { return &_class_data_; }

void TestCommonInfoList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestCommonInfoList *>(to)->MergeFrom(
      static_cast<const TestCommonInfoList &>(from));
}


void TestCommonInfoList::MergeFrom(const TestCommonInfoList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PBMsg.TestCommonInfoList)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  common_info_list_.MergeFrom(from.common_info_list_);
  common_type_list_.MergeFrom(from.common_type_list_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestCommonInfoList::CopyFrom(const TestCommonInfoList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBMsg.TestCommonInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestCommonInfoList::IsInitialized() const {
  return true;
}

void TestCommonInfoList::InternalSwap(TestCommonInfoList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  common_info_list_.InternalSwap(&other->common_info_list_);
  common_type_list_.InternalSwap(&other->common_type_list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestCommonInfoList::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMsgStruct_2eproto_getter, &descriptor_table_TestMsgStruct_2eproto_once,
      file_level_metadata_TestMsgStruct_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace PBMsg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PBMsg::TestCommonInfo* Arena::CreateMaybeMessage< ::PBMsg::TestCommonInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBMsg::TestCommonInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::PBMsg::TestCommonInfoList* Arena::CreateMaybeMessage< ::PBMsg::TestCommonInfoList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBMsg::TestCommonInfoList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
