if(LIBHV_PROJECT_INCLUDE_INCLUDED)
    return()
endif()
set(LIBHV_PROJECT_INCLUDE_INCLUDED TRUE)

set(LIBHV_GENERATED_CONFIG_HEADER "${CMAKE_CURRENT_BINARY_DIR}/hconfig.h")
set(LIBHV_GENERATED_INCLUDE_DIR "${CMAKE_CURRENT_BINARY_DIR}/include")

include_directories(BEFORE "${CMAKE_CURRENT_BINARY_DIR}")

function(libhv_redirect_hconfig_argument LIBHV_OUTPUT_VARIABLE)
    set(LIBHV_REDIRECTED_ARGS)
    foreach(LIBHV_REDIRECT_ARG IN LISTS ARGN)
        if("${LIBHV_REDIRECT_ARG}" STREQUAL "hconfig.h")
            list(APPEND LIBHV_REDIRECTED_ARGS "${LIBHV_GENERATED_CONFIG_HEADER}")
        else()
            list(APPEND LIBHV_REDIRECTED_ARGS "${LIBHV_REDIRECT_ARG}")
        endif()
    endforeach()
    set(${LIBHV_OUTPUT_VARIABLE} ${LIBHV_REDIRECTED_ARGS} PARENT_SCOPE)
endfunction()

function(configure_file)
    set(LIBHV_CONFIG_INPUT "${CMAKE_CURRENT_SOURCE_DIR}/hconfig.h.in")
    set(LIBHV_CONFIG_OUTPUT "${CMAKE_CURRENT_SOURCE_DIR}/hconfig.h")

    if(ARGC GREATER_EQUAL 2 AND "${ARGV0}" STREQUAL "${LIBHV_CONFIG_INPUT}" AND "${ARGV1}" STREQUAL "${LIBHV_CONFIG_OUTPUT}")
        set(LIBHV_CONFIGURE_FILE_ARGS ${ARGV})
        list(REMOVE_AT LIBHV_CONFIGURE_FILE_ARGS 1)
        list(INSERT LIBHV_CONFIGURE_FILE_ARGS 1 "${LIBHV_GENERATED_CONFIG_HEADER}")
        _configure_file(${LIBHV_CONFIGURE_FILE_ARGS})
    else()
        _configure_file(${ARGV})
    endif()
endfunction()

function(file)
    if(ARGC GREATER 0 AND "${ARGV0}" STREQUAL "INSTALL")
        set(LIBHV_NEXT_IS_DESTINATION OFF)
        foreach(LIBHV_FILE_ARG IN LISTS ARGV)
            if(LIBHV_NEXT_IS_DESTINATION)
                if("${LIBHV_FILE_ARG}" STREQUAL "${PROJECT_SOURCE_DIR}/include/hv")
                    return()
                endif()
                set(LIBHV_NEXT_IS_DESTINATION OFF)
            elseif("${LIBHV_FILE_ARG}" STREQUAL "DESTINATION")
                set(LIBHV_NEXT_IS_DESTINATION ON)
            endif()
        endforeach()

        libhv_redirect_hconfig_argument(LIBHV_FILE_ARGS ${ARGV})
        _file(${LIBHV_FILE_ARGS})
    else()
        _file(${ARGV})
    endif()
endfunction()

function(install)
    if(ARGC GREATER 0 AND "${ARGV0}" STREQUAL "FILES")
        libhv_redirect_hconfig_argument(LIBHV_INSTALL_ARGS ${ARGV})
        _install(${LIBHV_INSTALL_ARGS})
    else()
        _install(${ARGV})
    endif()
endfunction()

function(libhv_collect_target_headers LIBHV_SOURCE_OUTPUT_VARIABLE LIBHV_GENERATED_OUTPUT_VARIABLE LIBHV_ALL_OUTPUT_VARIABLE)
    set(LIBHV_SOURCE_HEADERS)
    set(LIBHV_GENERATED_HEADERS)
    set(LIBHV_ALL_HEADERS)

    if(DEFINED LIBHV_HEADERS)
        libhv_redirect_hconfig_argument(LIBHV_TARGET_HEADER_ARGS ${LIBHV_HEADERS})
        foreach(LIBHV_TARGET_HEADER IN LISTS LIBHV_TARGET_HEADER_ARGS)
            if(IS_ABSOLUTE "${LIBHV_TARGET_HEADER}")
                set(LIBHV_ABSOLUTE_HEADER "${LIBHV_TARGET_HEADER}")
            else()
                get_filename_component(LIBHV_ABSOLUTE_HEADER "${LIBHV_TARGET_HEADER}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
            endif()

            list(APPEND LIBHV_ALL_HEADERS "${LIBHV_ABSOLUTE_HEADER}")
            if("${LIBHV_ABSOLUTE_HEADER}" STREQUAL "${LIBHV_GENERATED_CONFIG_HEADER}")
                list(APPEND LIBHV_GENERATED_HEADERS "${LIBHV_ABSOLUTE_HEADER}")
            else()
                list(APPEND LIBHV_SOURCE_HEADERS "${LIBHV_ABSOLUTE_HEADER}")
            endif()
        endforeach()
    endif()

    set(${LIBHV_SOURCE_OUTPUT_VARIABLE} ${LIBHV_SOURCE_HEADERS} PARENT_SCOPE)
    set(${LIBHV_GENERATED_OUTPUT_VARIABLE} ${LIBHV_GENERATED_HEADERS} PARENT_SCOPE)
    set(${LIBHV_ALL_OUTPUT_VARIABLE} ${LIBHV_ALL_HEADERS} PARENT_SCOPE)
endfunction()

function(libhv_add_headers_to_target LIBHV_TARGET_NAME)
    if(NOT TARGET "${LIBHV_TARGET_NAME}")
        return()
    endif()

    libhv_collect_target_headers(LIBHV_SOURCE_HEADERS LIBHV_GENERATED_HEADERS LIBHV_ALL_HEADERS)
    if(NOT LIBHV_ALL_HEADERS)
        return()
    endif()

    set_source_files_properties(${LIBHV_ALL_HEADERS} PROPERTIES HEADER_FILE_ONLY TRUE)
    target_sources("${LIBHV_TARGET_NAME}" PRIVATE ${LIBHV_ALL_HEADERS})

    if(LIBHV_SOURCE_HEADERS)
        source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" PREFIX "Header Files" FILES ${LIBHV_SOURCE_HEADERS})
    endif()
    if(LIBHV_GENERATED_HEADERS)
        source_group("Header Files\\Generated" FILES ${LIBHV_GENERATED_HEADERS})
    endif()
endfunction()

function(add_library)
    _add_library(${ARGV})

    if(ARGC GREATER 0 AND ("${ARGV0}" STREQUAL "hv" OR "${ARGV0}" STREQUAL "hv_static"))
        libhv_add_headers_to_target("${ARGV0}")
    endif()
endfunction()

function(target_include_directories)
    _target_include_directories(${ARGV})

    if(ARGC GREATER 0 AND ("${ARGV0}" STREQUAL "hv" OR "${ARGV0}" STREQUAL "hv_static"))
        _target_include_directories("${ARGV0}" BEFORE PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
        _target_include_directories("${ARGV0}" BEFORE INTERFACE "$<BUILD_INTERFACE:${LIBHV_GENERATED_INCLUDE_DIR}>")
    endif()
endfunction()
