set(LIBHV_PRESET_ROOT "${CMAKE_CURRENT_LIST_DIR}/../libhv"    CACHE PATH "libhv preset root" FORCE)
set(LIBHV_THIRD_DIR   "${LIBHV_PRESET_ROOT}/../../../3rd-libs" CACHE PATH "libhv third-party dependency root" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(LIBHV_PLATFORM_DIR "windows")
    set(LIBHV_3RD_PLATFORM_DIR "x64-windows")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(LIBHV_PLATFORM_DIR "linux")
    set(LIBHV_3RD_PLATFORM_DIR "x64-ubuntu-24.04")
else()
    message(FATAL_ERROR "Unsupported host platform for libhv.cmake: ${CMAKE_HOST_SYSTEM_NAME}")
endif()

# Language standards
set(CMAKE_C_STANDARD 11 CACHE STRING "C standard" FORCE)
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C standard" FORCE)
set(CMAKE_C_EXTENSIONS ON CACHE BOOL "Keep GNU C extensions required by libhv headers" FORCE)
set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C++ standard" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C++ extensions" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    foreach(LIBHV_FLAG_VAR CMAKE_C_FLAGS CMAKE_CXX_FLAGS)
        set(LIBHV_FLAGS "${${LIBHV_FLAG_VAR}}")
        if(NOT LIBHV_FLAGS MATCHES "(^| )/MP( |$)")
            string(APPEND LIBHV_FLAGS " /MP")
        endif()
        if(NOT LIBHV_FLAGS MATCHES "(^| )/utf-8( |$)")
            string(APPEND LIBHV_FLAGS " /utf-8")
        endif()
        if(NOT LIBHV_FLAGS MATCHES "(^| )/wd4819( |$)")
            string(APPEND LIBHV_FLAGS " /wd4819")
        endif()
        set(${LIBHV_FLAG_VAR} "${LIBHV_FLAGS}" CACHE STRING "MSVC compiler flags" FORCE)
    endforeach()

    set(LIBHV_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    if(NOT LIBHV_CXX_FLAGS MATCHES "(^| )/EHsc( |$)")
        string(APPEND LIBHV_CXX_FLAGS " /EHsc")
    endif()
    set(CMAKE_CXX_FLAGS "${LIBHV_CXX_FLAGS}" CACHE STRING "MSVC C++ compiler flags" FORCE)

    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL" CACHE STRING "MSVC runtime library" FORCE)
endif()

# Core build behavior
set(LIBHV_OUTPUT_DIR               "${CMAKE_BINARY_DIR}/bin" CACHE PATH "libhv build output directory" FORCE)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${LIBHV_OUTPUT_DIR}"     CACHE PATH "Runtime output" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${LIBHV_OUTPUT_DIR}"     CACHE PATH "Library output" FORCE)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${LIBHV_OUTPUT_DIR}"     CACHE PATH "Archive output" FORCE)

foreach(LIBHV_OUTPUT_CONFIG Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${LIBHV_OUTPUT_CONFIG}" LIBHV_OUTPUT_CONFIG_UPPER)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${LIBHV_OUTPUT_CONFIG_UPPER} "${LIBHV_OUTPUT_DIR}" CACHE PATH "Runtime output for ${LIBHV_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${LIBHV_OUTPUT_CONFIG_UPPER} "${LIBHV_OUTPUT_DIR}" CACHE PATH "Library output for ${LIBHV_OUTPUT_CONFIG}" FORCE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${LIBHV_OUTPUT_CONFIG_UPPER} "${LIBHV_OUTPUT_DIR}" CACHE PATH "Archive output for ${LIBHV_OUTPUT_CONFIG}" FORCE)
endforeach()

function(libhv_copy_runtime_dependency LIBHV_RUNTIME_SOURCE)
    if(ARGC GREATER 1)
        set(LIBHV_RUNTIME_NAME "${ARGV1}")
    else()
        get_filename_component(LIBHV_RUNTIME_NAME "${LIBHV_RUNTIME_SOURCE}" NAME)
    endif()

    if(NOT EXISTS "${LIBHV_RUNTIME_SOURCE}")
        message(FATAL_ERROR "Missing libhv runtime dependency: ${LIBHV_RUNTIME_SOURCE}")
    endif()

    file(MAKE_DIRECTORY "${LIBHV_OUTPUT_DIR}")
    file(COPY_FILE "${LIBHV_RUNTIME_SOURCE}" "${LIBHV_OUTPUT_DIR}/${LIBHV_RUNTIME_NAME}" ONLY_IF_DIFFERENT)
endfunction()

# Build a single shared libhv artifact named "hv".
set(BUILD_SHARED_LIBS ON  CACHE BOOL "Build shared libraries" FORCE)
set(BUILD_SHARED      ON  CACHE BOOL "Build libhv shared library" FORCE)
set(BUILD_STATIC      OFF CACHE BOOL "Build libhv static library" FORCE)
set(BUILD_EXAMPLES    OFF CACHE BOOL "Build examples" FORCE)
set(BUILD_UNITTEST    OFF CACHE BOOL "Build unittest" FORCE)
set(BUILD_FOR_MT      OFF CACHE BOOL "Use /MT runtime" FORCE)

set(CMAKE_DEBUG_POSTFIX "" CACHE STRING "Do not suffix Debug artifacts" FORCE)
set(IMPORT_LIB_SUFFIX   "" CACHE STRING "Do not suffix Windows import libraries" FORCE)

# Enabled libhv modules and features
set(WITH_EVPP        ON CACHE BOOL "Enable C++ event loop wrapper" FORCE)
set(WITH_HTTP        ON CACHE BOOL "Enable HTTP support" FORCE)
set(WITH_HTTP_SERVER ON CACHE BOOL "Enable HTTP server support" FORCE)
set(WITH_HTTP_CLIENT ON CACHE BOOL "Enable HTTP client support" FORCE)
set(WITH_OPENSSL     ON CACHE BOOL "Enable OpenSSL TLS support" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(WITH_WEPOLL ON CACHE BOOL "Enable wepoll on Windows" FORCE)
endif()

# Disabled libhv modules and optional dependencies
set(WITH_PROTOCOL OFF CACHE BOOL "Disable extra protocol sources" FORCE)
set(WITH_MQTT     OFF CACHE BOOL "Disable MQTT support" FORCE)
set(WITH_CURL     OFF CACHE BOOL "Disable deprecated curl integration" FORCE)
set(WITH_NGHTTP2  OFF CACHE BOOL "Disable nghttp2 support" FORCE)
set(WITH_GNUTLS   OFF CACHE BOOL "Disable GnuTLS support" FORCE)
set(WITH_MBEDTLS  OFF CACHE BOOL "Disable mbedTLS support" FORCE)
set(WITH_KCP      OFF CACHE BOOL "Disable KCP support" FORCE)
set(ENABLE_UDS    OFF CACHE BOOL "Disable Unix domain sockets" FORCE)
set(USE_MULTIMAP  OFF CACHE BOOL "Disable MultiMap" FORCE)
set(ENABLE_WINDUMP OFF CACHE BOOL "Disable Windows minidump support" FORCE)

# External dependencies
set(OPENSSL_ROOT_DIR    "${LIBHV_THIRD_DIR}/openssl-3.0.20/${LIBHV_3RD_PLATFORM_DIR}" CACHE PATH "OpenSSL root" FORCE)
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include"                                 CACHE PATH "OpenSSL include directory" FORCE)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libssl.lib" CACHE FILEPATH "OpenSSL SSL library" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libcrypto.lib" CACHE FILEPATH "OpenSSL Crypto library" FORCE)
    libhv_copy_runtime_dependency("${OPENSSL_ROOT_DIR}/lib/libssl-3-x64.dll")
    libhv_copy_runtime_dependency("${OPENSSL_ROOT_DIR}/lib/libcrypto-3-x64.dll")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libssl.so.3" CACHE FILEPATH "OpenSSL SSL library" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/lib/libcrypto.so.3" CACHE FILEPATH "OpenSSL Crypto library" FORCE)
    libhv_copy_runtime_dependency("${OPENSSL_SSL_LIBRARY}")
    libhv_copy_runtime_dependency("${OPENSSL_CRYPTO_LIBRARY}")
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON CACHE BOOL "Use install RPATH for build-tree binaries" FORCE)
    set(CMAKE_BUILD_RPATH "$ORIGIN" CACHE STRING "Build-tree runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH "$ORIGIN" CACHE STRING "Install runtime library search path" FORCE)
    set(CMAKE_INSTALL_RPATH_USE_LINK_PATH OFF CACHE BOOL "Do not append link paths to install RPATH" FORCE)
    foreach(LIBHV_LINKER_FLAG_VAR CMAKE_SHARED_LINKER_FLAGS CMAKE_EXE_LINKER_FLAGS)
        set(LIBHV_LINKER_FLAGS "${${LIBHV_LINKER_FLAG_VAR}}")
        set(LIBHV_RPATH_LINK_FLAG "-Wl,-rpath-link,${OPENSSL_ROOT_DIR}/lib")
        string(FIND "${LIBHV_LINKER_FLAGS}" "${LIBHV_RPATH_LINK_FLAG}" LIBHV_RPATH_LINK_FOUND)
        if(LIBHV_RPATH_LINK_FOUND EQUAL -1)
            string(APPEND LIBHV_LINKER_FLAGS " ${LIBHV_RPATH_LINK_FLAG}")
        endif()
        set(${LIBHV_LINKER_FLAG_VAR} "${LIBHV_LINKER_FLAGS}" CACHE STRING "Linux linker flags" FORCE)
    endforeach()
endif()
