"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config
from django.core.exceptions import ImproperlyConfigured


# =============================================================================
# Paths
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# Environment helpers
# =============================================================================

def csv_config(name, default=''):
    """Read a comma-separated env var into a stripped list."""
    raw = config(name, default=default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def csv_unique_config(name, default=''):
    """Read a comma-separated env var into a stripped de-duplicated list."""
    values = []
    seen = set()
    for item in config(name, default=default).split(','):
        value = item.strip()
        if value and value not in seen:
            values.append(value)
            seen.add(value)
    return values


# =============================================================================
# Core runtime settings
# =============================================================================

# 开发环境默认开启 DEBUG，生产环境请显式设置 DJANGO_DEBUG=False
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

# 规则：
# - 开发环境（DEBUG=True）允许使用本地临时密钥，便于开箱运行
# - 非开发环境（DEBUG=False）必须显式通过环境变量 DJANGO_SECRET_KEY 提供
_env_secret_key = config('DJANGO_SECRET_KEY', default='')
if _env_secret_key:
    SECRET_KEY = _env_secret_key
elif DEBUG:
    SECRET_KEY = 'django-insecure-dev-key-only-for-development-do-not-use-in-production'
else:
    raise ImproperlyConfigured(
        '生产环境必须通过环境变量 DJANGO_SECRET_KEY 设置安全的 SECRET_KEY'
    )

_allowed_hosts_default = '127.0.0.1,localhost' if DEBUG else ''
ALLOWED_HOSTS = csv_config('DJANGO_ALLOWED_HOSTS', default=_allowed_hosts_default)

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        '生产环境必须通过环境变量 DJANGO_ALLOWED_HOSTS 设置具体的允许主机'
    )


# =============================================================================
# Django apps / middleware / templates
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'gmtool',
]

MIDDLEWARE = [
    'gmtool.middleware.AllowedHostErrorMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gmtool.middleware.IDIPFileMonitorMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gmtool.context_processors.gmtool_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# =============================================================================
# Database
# =============================================================================

DB_ENGINE = config('DB_ENGINE', default='sqlite').strip().lower()

if DB_ENGINE in ('sqlite', 'sqlite3', 'django.db.backends.sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
            'OPTIONS': {
                'timeout': config('DB_SQLITE_TIMEOUT', default=20, cast=int),
            },
        }
    }
elif DB_ENGINE in ('mysql', 'django.db.backends.mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='127.0.0.1'),
            'PORT': config('DB_PORT', default='3306'),
            'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=600, cast=int),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    raise ImproperlyConfigured(
        "DB_ENGINE 仅支持 sqlite 或 mysql"
    )

# =============================================================================
# Auth / password validation
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# Internationalization
# =============================================================================

LANGUAGE_CODE = 'zh-hans'
LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', '英文'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# =============================================================================
# Static files
# =============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# Application settings
# =============================================================================

LOGIN_URL = '/gmtool/login/'
CSRF_FAILURE_VIEW = 'gmtool.views.csrf_failure'

# IDIP / 命令定义
IDIP_API_URL = config('IDIP_API_URL', default='http://127.0.0.1:5510/cy_idip')
IDIP_TIMEOUT = config('IDIP_TIMEOUT', default=30, cast=int)
IDIP_JSON_PATH = config('IDIP_JSON_PATH', default=str(BASE_DIR / 'idip_commands.json'))
UPLOAD_MAX_SIZE = config('UPLOAD_MAX_SIZE', default=10 * 1024 * 1024, cast=int)

# 公告目录服接口
ANNOUNCEMENT_BASE_URL = config('ANNOUNCEMENT_BASE_URL', default='')
ANNOUNCEMENT_TIMEOUT = config('ANNOUNCEMENT_TIMEOUT', default=30, cast=float)
ANNOUNCEMENT_PLATFORMS = csv_unique_config(
    'ANNOUNCEMENT_PLATFORMS',
    default='CY',
)
ANNOUNCEMENT_CHANNELS = csv_unique_config(
    'ANNOUNCEMENT_CHANNELS',
    default='1001(XiaoMi)',
)

# 命令执行 / 展示
BATCH_EXECUTE_MAX_TARGETS = config('BATCH_EXECUTE_MAX_TARGETS', default=100, cast=int)
BATCH_EXECUTE_INTERVAL_MS = config('BATCH_EXECUTE_INTERVAL_MS', default=100, cast=int)
PAGE_SIZE = config('PAGE_SIZE', default=20, cast=int)

# 文件监控（仅作为开发便利功能；生产环境建议通过显式同步命令或上传后同步）
ENABLE_IDIP_FILE_MONITOR = config('ENABLE_IDIP_FILE_MONITOR', default=DEBUG, cast=bool)
IDIP_FILE_CHECK_INTERVAL = config('IDIP_FILE_CHECK_INTERVAL', default=30, cast=int)
IDIP_USE_HASH_CHECK = config('IDIP_USE_HASH_CHECK', default=False, cast=bool)

# 登录安全
LOGIN_MAX_ATTEMPTS = config('LOGIN_MAX_ATTEMPTS', default=5, cast=int)
LOGIN_LOCKOUT_SECONDS = config('LOGIN_LOCKOUT_SECONDS', default=300, cast=int)

# 日志脱敏
SENSITIVE_FIELDS = frozenset(
    csv_config(
        'SENSITIVE_FIELDS',
        default='password,passwd,pwd,token,access_token,refresh_token,secret,sign,signature,sessionid,cookie,authorization',
    )
)


# =============================================================================
# Proxy / session / CSRF
# =============================================================================

# 反向代理
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
TRUSTED_PROXY = config('DJANGO_TRUSTED_PROXY', default=False, cast=bool)
TRUSTED_PROXY_COUNT = config('DJANGO_TRUSTED_PROXY_COUNT', default=1, cast=int)

# 会话 / Cookie
SESSION_COOKIE_AGE = 86400              # Session 有效期 1 天（秒）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 浏览器关闭时过期
SESSION_COOKIE_HTTPONLY = True          # 禁止 JS 访问 Session Cookie
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)


# =============================================================================
# Security headers
# =============================================================================

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'


# =============================================================================
# Cache
# =============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'gmtool-cache',
    }
}


# =============================================================================
# Logging
# =============================================================================

LOG_DIR = BASE_DIR / 'logs'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'audit': {
            'format': '[{asctime}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'gmtool.logging_handlers.SafeTimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'audit.log'),
            'when': 'midnight',
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'audit',
        },
        'app_file': {
            'level': 'INFO',
            'class': 'gmtool.logging_handlers.SafeTimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'gmtool.log'),
            'when': 'midnight',
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'gmtool.audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gmtool': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
